//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.配载发货.FRM_PeiZaiFaHuoFenBao {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.配载发货.FRM_PeiZaiFaHuoFenBao.FRM_PeiZaiFaHuoFenBao")]
    public interface FRM_PeiZaiFaHuoFenBao {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PeiZaiFaHuoFenBao/FRM_PeiZaiFaHuo_Load_SelectKeHu", ReplyAction="http://tempuri.org/FRM_PeiZaiFaHuoFenBao/FRM_PeiZaiFaHuo_Load_SelectKeHuResponse")]
        System.Data.DataSet FRM_PeiZaiFaHuo_Load_SelectKeHu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PeiZaiFaHuoFenBao/btnChaXun_Select_Click_SelectDingDanXinX" +
            "i", ReplyAction="http://tempuri.org/FRM_PeiZaiFaHuoFenBao/btnChaXun_Select_Click_SelectDingDanXinX" +
            "iResponse")]
        System.Data.DataSet btnChaXun_Select_Click_SelectDingDanXinXi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PeiZaiFaHuoFenBao/dgvHuoYunDan_SelectionChanged_SelectDing" +
            "DanMingXi", ReplyAction="http://tempuri.org/FRM_PeiZaiFaHuoFenBao/dgvHuoYunDan_SelectionChanged_SelectDing" +
            "DanMingXiResponse")]
        System.Data.DataSet dgvHuoYunDan_SelectionChanged_SelectDingDanMingXi(int int货运单ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PeiZaiFaHuoFenBao/dgvMingXi_SelectionChanged_SelectFenBao", ReplyAction="http://tempuri.org/FRM_PeiZaiFaHuoFenBao/dgvMingXi_SelectionChanged_SelectFenBaoR" +
            "esponse")]
        System.Data.DataSet dgvMingXi_SelectionChanged_SelectFenBao(int int货运单明细ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PeiZaiFaHuoFenBao/btnChaXun_Select_Click_SelectDingDanXinX" +
            "i_DongTai", ReplyAction="http://tempuri.org/FRM_PeiZaiFaHuoFenBao/btnChaXun_Select_Click_SelectDingDanXinX" +
            "i_DongTaiResponse")]
        System.Data.DataSet btnChaXun_Select_Click_SelectDingDanXinXi_DongTai(string 动态条件);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_PeiZaiFaHuoFenBaoChannel : WCF物流管理系统_Client.BLL物流管理系统.配载发货.FRM_PeiZaiFaHuoFenBao.FRM_PeiZaiFaHuoFenBao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_PeiZaiFaHuoFenBaoClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.配载发货.FRM_PeiZaiFaHuoFenBao.FRM_PeiZaiFaHuoFenBao>, WCF物流管理系统_Client.BLL物流管理系统.配载发货.FRM_PeiZaiFaHuoFenBao.FRM_PeiZaiFaHuoFenBao {
        
        public FRM_PeiZaiFaHuoFenBaoClient() {
        }
        
        public FRM_PeiZaiFaHuoFenBaoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_PeiZaiFaHuoFenBaoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_PeiZaiFaHuoFenBaoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_PeiZaiFaHuoFenBaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_PeiZaiFaHuo_Load_SelectKeHu() {
            return base.Channel.FRM_PeiZaiFaHuo_Load_SelectKeHu();
        }
        
        public System.Data.DataSet btnChaXun_Select_Click_SelectDingDanXinXi() {
            return base.Channel.btnChaXun_Select_Click_SelectDingDanXinXi();
        }
        
        public System.Data.DataSet dgvHuoYunDan_SelectionChanged_SelectDingDanMingXi(int int货运单ID) {
            return base.Channel.dgvHuoYunDan_SelectionChanged_SelectDingDanMingXi(int货运单ID);
        }
        
        public System.Data.DataSet dgvMingXi_SelectionChanged_SelectFenBao(int int货运单明细ID) {
            return base.Channel.dgvMingXi_SelectionChanged_SelectFenBao(int货运单明细ID);
        }
        
        public System.Data.DataSet btnChaXun_Select_Click_SelectDingDanXinXi_DongTai(string 动态条件) {
            return base.Channel.btnChaXun_Select_Click_SelectDingDanXinXi_DongTai(动态条件);
        }
    }
}
