//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.报表统计.FRM_BaoBiaoDingDanLiuLan {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.报表统计.FRM_BaoBiaoDingDanLiuLan.FRM_BaoBiaoDingDanLiuLan")]
    public interface FRM_BaoBiaoDingDanLiuLan {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_BaoBiaoDingDanLiuLan/btnChaXun_Select_Click_ChaXunDingDan", ReplyAction="http://tempuri.org/FRM_BaoBiaoDingDanLiuLan/btnChaXun_Select_Click_ChaXunDingDanR" +
            "esponse")]
        System.Data.DataSet btnChaXun_Select_Click_ChaXunDingDan(string 开始时间, string 结束时间);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_BaoBiaoDingDanLiuLan/dgvDingDan_CellClick_ChaXunDingDanMin" +
            "gXi", ReplyAction="http://tempuri.org/FRM_BaoBiaoDingDanLiuLan/dgvDingDan_CellClick_ChaXunDingDanMin" +
            "gXiResponse")]
        System.Data.DataSet dgvDingDan_CellClick_ChaXunDingDanMingXi(string 货运单ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_BaoBiaoDingDanLiuLanChannel : WCF物流管理系统_Client.BLL物流管理系统.报表统计.FRM_BaoBiaoDingDanLiuLan.FRM_BaoBiaoDingDanLiuLan, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_BaoBiaoDingDanLiuLanClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.报表统计.FRM_BaoBiaoDingDanLiuLan.FRM_BaoBiaoDingDanLiuLan>, WCF物流管理系统_Client.BLL物流管理系统.报表统计.FRM_BaoBiaoDingDanLiuLan.FRM_BaoBiaoDingDanLiuLan {
        
        public FRM_BaoBiaoDingDanLiuLanClient() {
        }
        
        public FRM_BaoBiaoDingDanLiuLanClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_BaoBiaoDingDanLiuLanClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_BaoBiaoDingDanLiuLanClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_BaoBiaoDingDanLiuLanClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet btnChaXun_Select_Click_ChaXunDingDan(string 开始时间, string 结束时间) {
            return base.Channel.btnChaXun_Select_Click_ChaXunDingDan(开始时间, 结束时间);
        }
        
        public System.Data.DataSet dgvDingDan_CellClick_ChaXunDingDanMingXi(string 货运单ID) {
            return base.Channel.dgvDingDan_CellClick_ChaXunDingDanMingXi(货运单ID);
        }
    }
}
