//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_YongHuQuanXian_Insert {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.用户权限管理.BLL_YongHuQuanXian_Insert.BLL_YongHuQuanXian_Insert")]
    public interface BLL_YongHuQuanXian_Insert {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BLL_YongHuQuanXian_Insert/FRM_YongHuQuanXian_Insert_Load_ChaXu" +
            "nQuanXianZu", ReplyAction="http://tempuri.org/BLL_YongHuQuanXian_Insert/FRM_YongHuQuanXian_Insert_Load_ChaXu" +
            "nQuanXianZuResponse")]
        System.Data.DataSet FRM_YongHuQuanXian_Insert_Load_ChaXunQuanXianZu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BLL_YongHuQuanXian_Insert/FRM_YongHuQuanXian_Insert_Load_ChaXu" +
            "nYuanGong", ReplyAction="http://tempuri.org/BLL_YongHuQuanXian_Insert/FRM_YongHuQuanXian_Insert_Load_ChaXu" +
            "nYuanGongResponse")]
        System.Data.DataSet FRM_YongHuQuanXian_Insert_Load_ChaXunYuanGong();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BLL_YongHuQuanXian_Insert/FRM_YongHuQuanXian_Insert_btnQueDing" +
            "_Click", ReplyAction="http://tempuri.org/BLL_YongHuQuanXian_Insert/FRM_YongHuQuanXian_Insert_btnQueDing" +
            "_ClickResponse")]
        int FRM_YongHuQuanXian_Insert_btnQueDing_Click(string 账号, string 密码, int 权限组ID, int 员工ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BLL_YongHuQuanXian_InsertChannel : WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_YongHuQuanXian_Insert.BLL_YongHuQuanXian_Insert, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BLL_YongHuQuanXian_InsertClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_YongHuQuanXian_Insert.BLL_YongHuQuanXian_Insert>, WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_YongHuQuanXian_Insert.BLL_YongHuQuanXian_Insert {
        
        public BLL_YongHuQuanXian_InsertClient() {
        }
        
        public BLL_YongHuQuanXian_InsertClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BLL_YongHuQuanXian_InsertClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BLL_YongHuQuanXian_InsertClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BLL_YongHuQuanXian_InsertClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_YongHuQuanXian_Insert_Load_ChaXunQuanXianZu() {
            return base.Channel.FRM_YongHuQuanXian_Insert_Load_ChaXunQuanXianZu();
        }
        
        public System.Data.DataSet FRM_YongHuQuanXian_Insert_Load_ChaXunYuanGong() {
            return base.Channel.FRM_YongHuQuanXian_Insert_Load_ChaXunYuanGong();
        }
        
        public int FRM_YongHuQuanXian_Insert_btnQueDing_Click(string 账号, string 密码, int 权限组ID, int 员工ID) {
            return base.Channel.FRM_YongHuQuanXian_Insert_btnQueDing_Click(账号, 密码, 权限组ID, 员工ID);
        }
    }
}
