//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.报表统计.FRM_ShenHeHuoPinTongJi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.报表统计.FRM_ShenHeHuoPinTongJi.FRM_ShenHeHuoPinTongJi")]
    public interface FRM_ShenHeHuoPinTongJi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ShenHeHuoPinTongJi/FRM_ShenHeHuoPinTongJi_Load_ChaXunHuiZo" +
            "ng", ReplyAction="http://tempuri.org/FRM_ShenHeHuoPinTongJi/FRM_ShenHeHuoPinTongJi_Load_ChaXunHuiZo" +
            "ngResponse")]
        System.Data.DataSet FRM_ShenHeHuoPinTongJi_Load_ChaXunHuiZong();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_ShenHeHuoPinTongJiChannel : WCF物流管理系统_Client.BLL物流管理系统.报表统计.FRM_ShenHeHuoPinTongJi.FRM_ShenHeHuoPinTongJi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_ShenHeHuoPinTongJiClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.报表统计.FRM_ShenHeHuoPinTongJi.FRM_ShenHeHuoPinTongJi>, WCF物流管理系统_Client.BLL物流管理系统.报表统计.FRM_ShenHeHuoPinTongJi.FRM_ShenHeHuoPinTongJi {
        
        public FRM_ShenHeHuoPinTongJiClient() {
        }
        
        public FRM_ShenHeHuoPinTongJiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_ShenHeHuoPinTongJiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_ShenHeHuoPinTongJiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_ShenHeHuoPinTongJiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_ShenHeHuoPinTongJi_Load_ChaXunHuiZong() {
            return base.Channel.FRM_ShenHeHuoPinTongJi_Load_ChaXunHuiZong();
        }
    }
}
