//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34003
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.车辆状态.FRM_CheLiangZhuangTai {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.车辆状态.FRM_CheLiangZhuangTai.FRM_CheLiangZhuangTai")]
    public interface FRM_CheLiangZhuangTai {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangZhuangTai/tsbShanChu_Delete_Click_ShanChuCheLiang", ReplyAction="http://tempuri.org/FRM_CheLiangZhuangTai/tsbShanChu_Delete_Click_ShanChuCheLiangR" +
            "esponse")]
        int tsbShanChu_Delete_Click_ShanChuCheLiang(string strCheLiangID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangZhuangTai/btnChaXun_Select_Click_DuoTiaoJianChaXun" +
            "CheLiang", ReplyAction="http://tempuri.org/FRM_CheLiangZhuangTai/btnChaXun_Select_Click_DuoTiaoJianChaXun" +
            "CheLiangResponse")]
        System.Data.DataSet btnChaXun_Select_Click_DuoTiaoJianChaXunCheLiang(string strFaCheWangDianID, string strMuDiWangDianID, string strZhuangTaiID, string strSiJiMingCheng);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangZhuangTai/FRM_CheLiangZhuangTai_Load_ChaXunQuanBuC" +
            "heLiang", ReplyAction="http://tempuri.org/FRM_CheLiangZhuangTai/FRM_CheLiangZhuangTai_Load_ChaXunQuanBuC" +
            "heLiangResponse")]
        System.Data.DataSet FRM_CheLiangZhuangTai_Load_ChaXunQuanBuCheLiang();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangZhuangTai/FRM_CheLiangZhuangTai_Load_ChaXunWangDia" +
            "n", ReplyAction="http://tempuri.org/FRM_CheLiangZhuangTai/FRM_CheLiangZhuangTai_Load_ChaXunWangDia" +
            "nResponse")]
        System.Data.DataSet FRM_CheLiangZhuangTai_Load_ChaXunWangDian();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangZhuangTai/FRM_CheLiangZhuangTai_Load_ChaXunZhuangT" +
            "ai", ReplyAction="http://tempuri.org/FRM_CheLiangZhuangTai/FRM_CheLiangZhuangTai_Load_ChaXunZhuangT" +
            "aiResponse")]
        System.Data.DataSet FRM_CheLiangZhuangTai_Load_ChaXunZhuangTai();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangZhuangTai/ToolStripMenuItem_Click_XiuGaiZhuangTai", ReplyAction="http://tempuri.org/FRM_CheLiangZhuangTai/ToolStripMenuItem_Click_XiuGaiZhuangTaiR" +
            "esponse")]
        int ToolStripMenuItem_Click_XiuGaiZhuangTai(string 状态ID, string 车辆ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_CheLiangZhuangTaiChannel : WCF物流管理系统_Client.BLL物流管理系统.车辆状态.FRM_CheLiangZhuangTai.FRM_CheLiangZhuangTai, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_CheLiangZhuangTaiClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.车辆状态.FRM_CheLiangZhuangTai.FRM_CheLiangZhuangTai>, WCF物流管理系统_Client.BLL物流管理系统.车辆状态.FRM_CheLiangZhuangTai.FRM_CheLiangZhuangTai {
        
        public FRM_CheLiangZhuangTaiClient() {
        }
        
        public FRM_CheLiangZhuangTaiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_CheLiangZhuangTaiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_CheLiangZhuangTaiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_CheLiangZhuangTaiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int tsbShanChu_Delete_Click_ShanChuCheLiang(string strCheLiangID) {
            return base.Channel.tsbShanChu_Delete_Click_ShanChuCheLiang(strCheLiangID);
        }
        
        public System.Data.DataSet btnChaXun_Select_Click_DuoTiaoJianChaXunCheLiang(string strFaCheWangDianID, string strMuDiWangDianID, string strZhuangTaiID, string strSiJiMingCheng) {
            return base.Channel.btnChaXun_Select_Click_DuoTiaoJianChaXunCheLiang(strFaCheWangDianID, strMuDiWangDianID, strZhuangTaiID, strSiJiMingCheng);
        }
        
        public System.Data.DataSet FRM_CheLiangZhuangTai_Load_ChaXunQuanBuCheLiang() {
            return base.Channel.FRM_CheLiangZhuangTai_Load_ChaXunQuanBuCheLiang();
        }
        
        public System.Data.DataSet FRM_CheLiangZhuangTai_Load_ChaXunWangDian() {
            return base.Channel.FRM_CheLiangZhuangTai_Load_ChaXunWangDian();
        }
        
        public System.Data.DataSet FRM_CheLiangZhuangTai_Load_ChaXunZhuangTai() {
            return base.Channel.FRM_CheLiangZhuangTai_Load_ChaXunZhuangTai();
        }
        
        public int ToolStripMenuItem_Click_XiuGaiZhuangTai(string 状态ID, string 车辆ID) {
            return base.Channel.ToolStripMenuItem_Click_XiuGaiZhuangTai(状态ID, 车辆ID);
        }
    }
}
