//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.订单管理.DingDanGuanLi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.订单管理.DingDanGuanLi.DingDanGuanLi")]
    public interface DingDanGuanLi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi/FRM_DingDanGuanLi_Load_SelectZhuangTai", ReplyAction="http://tempuri.org/DingDanGuanLi/FRM_DingDanGuanLi_Load_SelectZhuangTaiResponse")]
        System.Data.DataSet FRM_DingDanGuanLi_Load_SelectZhuangTai();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi/FRM_DingDanGuanLi_Load_SelectHuoMing", ReplyAction="http://tempuri.org/DingDanGuanLi/FRM_DingDanGuanLi_Load_SelectHuoMingResponse")]
        System.Data.DataSet FRM_DingDanGuanLi_Load_SelectHuoMing();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi/FRM_DingDanGuanLi_Load_SelectKeHu", ReplyAction="http://tempuri.org/DingDanGuanLi/FRM_DingDanGuanLi_Load_SelectKeHuResponse")]
        System.Data.DataSet FRM_DingDanGuanLi_Load_SelectKeHu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi/FRM_DingDanGuanLi_Load_SelectAllDingDan", ReplyAction="http://tempuri.org/DingDanGuanLi/FRM_DingDanGuanLi_Load_SelectAllDingDanResponse")]
        System.Data.DataSet FRM_DingDanGuanLi_Load_SelectAllDingDan();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi/FRM_DingDanGuanLi_Load_SelectDingDanByRiQi", ReplyAction="http://tempuri.org/DingDanGuanLi/FRM_DingDanGuanLi_Load_SelectDingDanByRiQiRespon" +
            "se")]
        System.Data.DataSet FRM_DingDanGuanLi_Load_SelectDingDanByRiQi(System.DateTime kaishi, System.DateTime jieshu, bool shenhefou);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi/FRM_DingDanGuanLi_Load_SelectDingDanByHuoWuID", ReplyAction="http://tempuri.org/DingDanGuanLi/FRM_DingDanGuanLi_Load_SelectDingDanByHuoWuIDRes" +
            "ponse")]
        System.Data.DataSet FRM_DingDanGuanLi_Load_SelectDingDanByHuoWuID(int huowuid, bool shenhefou);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi/dgvHuoYunDan_SelectionChanged_SelectHuoYunDanMin" +
            "gXi", ReplyAction="http://tempuri.org/DingDanGuanLi/dgvHuoYunDan_SelectionChanged_SelectHuoYunDanMin" +
            "gXiResponse")]
        System.Data.DataSet dgvHuoYunDan_SelectionChanged_SelectHuoYunDanMingXi(int HuoYunDanID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi/FRM_DingDanGuanLi_Load_SelectHuoYunDanCount", ReplyAction="http://tempuri.org/DingDanGuanLi/FRM_DingDanGuanLi_Load_SelectHuoYunDanCountRespo" +
            "nse")]
        int FRM_DingDanGuanLi_Load_SelectHuoYunDanCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi/FRM_DingDanGuanLi_Load_SelectHuoYunDanByFenYe", ReplyAction="http://tempuri.org/DingDanGuanLi/FRM_DingDanGuanLi_Load_SelectHuoYunDanByFenYeRes" +
            "ponse")]
        System.Data.DataSet FRM_DingDanGuanLi_Load_SelectHuoYunDanByFenYe(int pageSize, int pageNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi/tspBtnShanChuDingDan_Click_DeleteHuoYunDan", ReplyAction="http://tempuri.org/DingDanGuanLi/tspBtnShanChuDingDan_Click_DeleteHuoYunDanRespon" +
            "se")]
        int tspBtnShanChuDingDan_Click_DeleteHuoYunDan(int 货运单ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi/tspBtnShanChuDingDan_Click_DeleteHuoYunDanMingXi" +
            "", ReplyAction="http://tempuri.org/DingDanGuanLi/tspBtnShanChuDingDan_Click_DeleteHuoYunDanMingXi" +
            "Response")]
        int tspBtnShanChuDingDan_Click_DeleteHuoYunDanMingXi(int 货运单ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi/dgvHuoYunDan_CellClick_UpdateShenHe", ReplyAction="http://tempuri.org/DingDanGuanLi/dgvHuoYunDan_CellClick_UpdateShenHeResponse")]
        int dgvHuoYunDan_CellClick_UpdateShenHe(int 货运单ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi/dgvHuoYunDan_CellClick_InsertFenBao", ReplyAction="http://tempuri.org/DingDanGuanLi/dgvHuoYunDan_CellClick_InsertFenBaoResponse")]
        int dgvHuoYunDan_CellClick_InsertFenBao(int 货运单明细ID, decimal 分包数量);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi/Search_WuLiuGenZhongXinXi", ReplyAction="http://tempuri.org/DingDanGuanLi/Search_WuLiuGenZhongXinXiResponse")]
        System.Data.DataSet Search_WuLiuGenZhongXinXi(string 订单流水号);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DingDanGuanLiChannel : WCF物流管理系统_Client.BLL物流管理系统.订单管理.DingDanGuanLi.DingDanGuanLi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DingDanGuanLiClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.订单管理.DingDanGuanLi.DingDanGuanLi>, WCF物流管理系统_Client.BLL物流管理系统.订单管理.DingDanGuanLi.DingDanGuanLi {
        
        public DingDanGuanLiClient() {
        }
        
        public DingDanGuanLiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DingDanGuanLiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DingDanGuanLiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DingDanGuanLiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_DingDanGuanLi_Load_SelectZhuangTai() {
            return base.Channel.FRM_DingDanGuanLi_Load_SelectZhuangTai();
        }
        
        public System.Data.DataSet FRM_DingDanGuanLi_Load_SelectHuoMing() {
            return base.Channel.FRM_DingDanGuanLi_Load_SelectHuoMing();
        }
        
        public System.Data.DataSet FRM_DingDanGuanLi_Load_SelectKeHu() {
            return base.Channel.FRM_DingDanGuanLi_Load_SelectKeHu();
        }
        
        public System.Data.DataSet FRM_DingDanGuanLi_Load_SelectAllDingDan() {
            return base.Channel.FRM_DingDanGuanLi_Load_SelectAllDingDan();
        }
        
        public System.Data.DataSet FRM_DingDanGuanLi_Load_SelectDingDanByRiQi(System.DateTime kaishi, System.DateTime jieshu, bool shenhefou) {
            return base.Channel.FRM_DingDanGuanLi_Load_SelectDingDanByRiQi(kaishi, jieshu, shenhefou);
        }
        
        public System.Data.DataSet FRM_DingDanGuanLi_Load_SelectDingDanByHuoWuID(int huowuid, bool shenhefou) {
            return base.Channel.FRM_DingDanGuanLi_Load_SelectDingDanByHuoWuID(huowuid, shenhefou);
        }
        
        public System.Data.DataSet dgvHuoYunDan_SelectionChanged_SelectHuoYunDanMingXi(int HuoYunDanID) {
            return base.Channel.dgvHuoYunDan_SelectionChanged_SelectHuoYunDanMingXi(HuoYunDanID);
        }
        
        public int FRM_DingDanGuanLi_Load_SelectHuoYunDanCount() {
            return base.Channel.FRM_DingDanGuanLi_Load_SelectHuoYunDanCount();
        }
        
        public System.Data.DataSet FRM_DingDanGuanLi_Load_SelectHuoYunDanByFenYe(int pageSize, int pageNum) {
            return base.Channel.FRM_DingDanGuanLi_Load_SelectHuoYunDanByFenYe(pageSize, pageNum);
        }
        
        public int tspBtnShanChuDingDan_Click_DeleteHuoYunDan(int 货运单ID) {
            return base.Channel.tspBtnShanChuDingDan_Click_DeleteHuoYunDan(货运单ID);
        }
        
        public int tspBtnShanChuDingDan_Click_DeleteHuoYunDanMingXi(int 货运单ID) {
            return base.Channel.tspBtnShanChuDingDan_Click_DeleteHuoYunDanMingXi(货运单ID);
        }
        
        public int dgvHuoYunDan_CellClick_UpdateShenHe(int 货运单ID) {
            return base.Channel.dgvHuoYunDan_CellClick_UpdateShenHe(货运单ID);
        }
        
        public int dgvHuoYunDan_CellClick_InsertFenBao(int 货运单明细ID, decimal 分包数量) {
            return base.Channel.dgvHuoYunDan_CellClick_InsertFenBao(货运单明细ID, 分包数量);
        }
        
        public System.Data.DataSet Search_WuLiuGenZhongXinXi(string 订单流水号) {
            return base.Channel.Search_WuLiuGenZhongXinXi(订单流水号);
        }
    }
}
