//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_XuanZheQuanXianZu {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.用户权限管理.BLL_XuanZheQuanXianZu.BLL_XuanZheQuanXianZu")]
    public interface BLL_XuanZheQuanXianZu {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BLL_XuanZheQuanXianZu/FRM_XuanZheQuanXianZu_Load_ChaXunQuanXia" +
            "nZu", ReplyAction="http://tempuri.org/BLL_XuanZheQuanXianZu/FRM_XuanZheQuanXianZu_Load_ChaXunQuanXia" +
            "nZuResponse")]
        System.Data.DataSet FRM_XuanZheQuanXianZu_Load_ChaXunQuanXianZu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BLL_XuanZheQuanXianZu/FRM_XuanZheQuanXianZu_btnQueDing_Click", ReplyAction="http://tempuri.org/BLL_XuanZheQuanXianZu/FRM_XuanZheQuanXianZu_btnQueDing_ClickRe" +
            "sponse")]
        int FRM_XuanZheQuanXianZu_btnQueDing_Click(int 用户ID, int 权限组ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BLL_XuanZheQuanXianZuChannel : WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_XuanZheQuanXianZu.BLL_XuanZheQuanXianZu, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BLL_XuanZheQuanXianZuClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_XuanZheQuanXianZu.BLL_XuanZheQuanXianZu>, WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_XuanZheQuanXianZu.BLL_XuanZheQuanXianZu {
        
        public BLL_XuanZheQuanXianZuClient() {
        }
        
        public BLL_XuanZheQuanXianZuClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BLL_XuanZheQuanXianZuClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BLL_XuanZheQuanXianZuClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BLL_XuanZheQuanXianZuClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_XuanZheQuanXianZu_Load_ChaXunQuanXianZu() {
            return base.Channel.FRM_XuanZheQuanXianZu_Load_ChaXunQuanXianZu();
        }
        
        public int FRM_XuanZheQuanXianZu_btnQueDing_Click(int 用户ID, int 权限组ID) {
            return base.Channel.FRM_XuanZheQuanXianZu_btnQueDing_Click(用户ID, 权限组ID);
        }
    }
}
