//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_QuanXianZu_Update {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.用户权限管理.BLL_QuanXianZu_Update.BLL_QuanXianZu_Update")]
    public interface BLL_QuanXianZu_Update {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BLL_QuanXianZu_Update/FRM_QuanXianZu_Update_Load_ChaXunQuanXia" +
            "nZuMoKuai", ReplyAction="http://tempuri.org/BLL_QuanXianZu_Update/FRM_QuanXianZu_Update_Load_ChaXunQuanXia" +
            "nZuMoKuaiResponse")]
        System.Data.DataSet FRM_QuanXianZu_Update_Load_ChaXunQuanXianZuMoKuai(int 权限组ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BLL_QuanXianZu_Update/FRM_QuanXianZu_Update_btnQueDing_Click", ReplyAction="http://tempuri.org/BLL_QuanXianZu_Update/FRM_QuanXianZu_Update_btnQueDing_ClickRe" +
            "sponse")]
        int FRM_QuanXianZu_Update_btnQueDing_Click(int[] 模块ID, string 权限组名称, int 权限组ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BLL_QuanXianZu_UpdateChannel : WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_QuanXianZu_Update.BLL_QuanXianZu_Update, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BLL_QuanXianZu_UpdateClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_QuanXianZu_Update.BLL_QuanXianZu_Update>, WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_QuanXianZu_Update.BLL_QuanXianZu_Update {
        
        public BLL_QuanXianZu_UpdateClient() {
        }
        
        public BLL_QuanXianZu_UpdateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BLL_QuanXianZu_UpdateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BLL_QuanXianZu_UpdateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BLL_QuanXianZu_UpdateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_QuanXianZu_Update_Load_ChaXunQuanXianZuMoKuai(int 权限组ID) {
            return base.Channel.FRM_QuanXianZu_Update_Load_ChaXunQuanXianZuMoKuai(权限组ID);
        }
        
        public int FRM_QuanXianZu_Update_btnQueDing_Click(int[] 模块ID, string 权限组名称, int 权限组ID) {
            return base.Channel.FRM_QuanXianZu_Update_btnQueDing_Click(模块ID, 权限组名称, 权限组ID);
        }
    }
}
