//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.线路管理.FRM_XianLuGuanLi_Update {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.线路管理.FRM_XianLuGuanLi_Update.FRM_XianLuGuanLi_Update")]
    public interface FRM_XianLuGuanLi_Update {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_XianLuGuanLi_Update/FRM_XianLuGuanLi_Update_Load_ChaXunXia" +
            "nLuXinXi", ReplyAction="http://tempuri.org/FRM_XianLuGuanLi_Update/FRM_XianLuGuanLi_Update_Load_ChaXunXia" +
            "nLuXinXiResponse")]
        System.Data.DataSet FRM_XianLuGuanLi_Update_Load_ChaXunXianLuXinXi(string 线路ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_XianLuGuanLi_Update/FRM_XianLuGuanLi_Update_Load_ChaXunXia" +
            "nLuMingXiXinXi", ReplyAction="http://tempuri.org/FRM_XianLuGuanLi_Update/FRM_XianLuGuanLi_Update_Load_ChaXunXia" +
            "nLuMingXiXinXiResponse")]
        System.Data.DataSet FRM_XianLuGuanLi_Update_Load_ChaXunXianLuMingXiXinXi(string 线路ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_XianLuGuanLi_Update/btnBaoCunXianLu_Update_Click_ShanChuXi" +
            "anLuMingXi", ReplyAction="http://tempuri.org/FRM_XianLuGuanLi_Update/btnBaoCunXianLu_Update_Click_ShanChuXi" +
            "anLuMingXiResponse")]
        int btnBaoCunXianLu_Update_Click_ShanChuXianLuMingXi(string 线路ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_XianLuGuanLi_Update/btnBaoCunXianLu_Update_Click_XiuGaiXia" +
            "nLu", ReplyAction="http://tempuri.org/FRM_XianLuGuanLi_Update/btnBaoCunXianLu_Update_Click_XiuGaiXia" +
            "nLuResponse")]
        int btnBaoCunXianLu_Update_Click_XiuGaiXianLu(string 线路名称, string 助记码, string 线路ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_XianLuGuanLi_UpdateChannel : WCF物流管理系统_Client.BLL物流管理系统.线路管理.FRM_XianLuGuanLi_Update.FRM_XianLuGuanLi_Update, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_XianLuGuanLi_UpdateClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.线路管理.FRM_XianLuGuanLi_Update.FRM_XianLuGuanLi_Update>, WCF物流管理系统_Client.BLL物流管理系统.线路管理.FRM_XianLuGuanLi_Update.FRM_XianLuGuanLi_Update {
        
        public FRM_XianLuGuanLi_UpdateClient() {
        }
        
        public FRM_XianLuGuanLi_UpdateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_XianLuGuanLi_UpdateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_XianLuGuanLi_UpdateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_XianLuGuanLi_UpdateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_XianLuGuanLi_Update_Load_ChaXunXianLuXinXi(string 线路ID) {
            return base.Channel.FRM_XianLuGuanLi_Update_Load_ChaXunXianLuXinXi(线路ID);
        }
        
        public System.Data.DataSet FRM_XianLuGuanLi_Update_Load_ChaXunXianLuMingXiXinXi(string 线路ID) {
            return base.Channel.FRM_XianLuGuanLi_Update_Load_ChaXunXianLuMingXiXinXi(线路ID);
        }
        
        public int btnBaoCunXianLu_Update_Click_ShanChuXianLuMingXi(string 线路ID) {
            return base.Channel.btnBaoCunXianLu_Update_Click_ShanChuXianLuMingXi(线路ID);
        }
        
        public int btnBaoCunXianLu_Update_Click_XiuGaiXianLu(string 线路名称, string 助记码, string 线路ID) {
            return base.Channel.btnBaoCunXianLu_Update_Click_XiuGaiXianLu(线路名称, 助记码, 线路ID);
        }
    }
}
