//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_YongHuQuanXian_Update {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.用户权限管理.BLL_YongHuQuanXian_Update.BLL_YongHuQuanXian_Update")]
    public interface BLL_YongHuQuanXian_Update {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BLL_YongHuQuanXian_Update/FRM_YongHuQuanXian_Update_ChaXunQuan" +
            "XianZu", ReplyAction="http://tempuri.org/BLL_YongHuQuanXian_Update/FRM_YongHuQuanXian_Update_ChaXunQuan" +
            "XianZuResponse")]
        System.Data.DataSet FRM_YongHuQuanXian_Update_ChaXunQuanXianZu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BLL_YongHuQuanXian_Update/FRM_YongHuQuanXian_Update_Load_ChaXu" +
            "nYuanGong", ReplyAction="http://tempuri.org/BLL_YongHuQuanXian_Update/FRM_YongHuQuanXian_Update_Load_ChaXu" +
            "nYuanGongResponse")]
        System.Data.DataSet FRM_YongHuQuanXian_Update_Load_ChaXunYuanGong();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BLL_YongHuQuanXian_Update/FRM_YongHuQuanXian_Update_btnQueDing" +
            "_Click", ReplyAction="http://tempuri.org/BLL_YongHuQuanXian_Update/FRM_YongHuQuanXian_Update_btnQueDing" +
            "_ClickResponse")]
        int FRM_YongHuQuanXian_Update_btnQueDing_Click(string 账号, string 密码, int 权限组ID, int 员工ID, int 用户ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BLL_YongHuQuanXian_UpdateChannel : WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_YongHuQuanXian_Update.BLL_YongHuQuanXian_Update, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BLL_YongHuQuanXian_UpdateClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_YongHuQuanXian_Update.BLL_YongHuQuanXian_Update>, WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_YongHuQuanXian_Update.BLL_YongHuQuanXian_Update {
        
        public BLL_YongHuQuanXian_UpdateClient() {
        }
        
        public BLL_YongHuQuanXian_UpdateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BLL_YongHuQuanXian_UpdateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BLL_YongHuQuanXian_UpdateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BLL_YongHuQuanXian_UpdateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_YongHuQuanXian_Update_ChaXunQuanXianZu() {
            return base.Channel.FRM_YongHuQuanXian_Update_ChaXunQuanXianZu();
        }
        
        public System.Data.DataSet FRM_YongHuQuanXian_Update_Load_ChaXunYuanGong() {
            return base.Channel.FRM_YongHuQuanXian_Update_Load_ChaXunYuanGong();
        }
        
        public int FRM_YongHuQuanXian_Update_btnQueDing_Click(string 账号, string 密码, int 权限组ID, int 员工ID, int 用户ID) {
            return base.Channel.FRM_YongHuQuanXian_Update_btnQueDing_Click(账号, 密码, 权限组ID, 员工ID, 用户ID);
        }
    }
}
