//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.司机管理.BLL_FRM_SiJiGuanLi_Update {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.司机管理.BLL_FRM_SiJiGuanLi_Update.BLL_FRM_SiJiGuanLi_Update")]
    public interface BLL_FRM_SiJiGuanLi_Update {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BLL_FRM_SiJiGuanLi_Update/FRM_SiJiGuanLi_Load_Update_ChaXunZhu" +
            "nJiaCheXin", ReplyAction="http://tempuri.org/BLL_FRM_SiJiGuanLi_Update/FRM_SiJiGuanLi_Load_Update_ChaXunZhu" +
            "nJiaCheXinResponse")]
        System.Data.DataSet FRM_SiJiGuanLi_Load_Update_ChaXunZhunJiaCheXin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BLL_FRM_SiJiGuanLi_Update/btnQueDing_Click_XiuGaiSiJi", ReplyAction="http://tempuri.org/BLL_FRM_SiJiGuanLi_Update/btnQueDing_Click_XiuGaiSiJiResponse")]
        bool btnQueDing_Click_XiuGaiSiJi(string 司机名称, string 出生日期, string 联系电话, string 联系地址, string 身份证号, string 驾驶证号, string 备注, int 机构组织ID, int 准驾车型ID, bool 是否离职, int 司机ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BLL_FRM_SiJiGuanLi_UpdateChannel : WCF物流管理系统_Client.BLL物流管理系统.司机管理.BLL_FRM_SiJiGuanLi_Update.BLL_FRM_SiJiGuanLi_Update, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BLL_FRM_SiJiGuanLi_UpdateClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.司机管理.BLL_FRM_SiJiGuanLi_Update.BLL_FRM_SiJiGuanLi_Update>, WCF物流管理系统_Client.BLL物流管理系统.司机管理.BLL_FRM_SiJiGuanLi_Update.BLL_FRM_SiJiGuanLi_Update {
        
        public BLL_FRM_SiJiGuanLi_UpdateClient() {
        }
        
        public BLL_FRM_SiJiGuanLi_UpdateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BLL_FRM_SiJiGuanLi_UpdateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BLL_FRM_SiJiGuanLi_UpdateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BLL_FRM_SiJiGuanLi_UpdateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_SiJiGuanLi_Load_Update_ChaXunZhunJiaCheXin() {
            return base.Channel.FRM_SiJiGuanLi_Load_Update_ChaXunZhunJiaCheXin();
        }
        
        public bool btnQueDing_Click_XiuGaiSiJi(string 司机名称, string 出生日期, string 联系电话, string 联系地址, string 身份证号, string 驾驶证号, string 备注, int 机构组织ID, int 准驾车型ID, bool 是否离职, int 司机ID) {
            return base.Channel.btnQueDing_Click_XiuGaiSiJi(司机名称, 出生日期, 联系电话, 联系地址, 身份证号, 驾驶证号, 备注, 机构组织ID, 准驾车型ID, 是否离职, 司机ID);
        }
    }
}
