//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.司机管理.BLL_FRM_XuanZheJiGou {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.司机管理.BLL_FRM_XuanZheJiGou.BLL_FRM_XuanZheJiGou")]
    public interface BLL_FRM_XuanZheJiGou {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BLL_FRM_XuanZheJiGou/FRM_XuanZheJiGou_Load_ChaXunJiGouZuZhi", ReplyAction="http://tempuri.org/BLL_FRM_XuanZheJiGou/FRM_XuanZheJiGou_Load_ChaXunJiGouZuZhiRes" +
            "ponse")]
        System.Data.DataSet FRM_XuanZheJiGou_Load_ChaXunJiGouZuZhi(int 机构组织ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BLL_FRM_XuanZheJiGouChannel : WCF物流管理系统_Client.BLL物流管理系统.司机管理.BLL_FRM_XuanZheJiGou.BLL_FRM_XuanZheJiGou, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BLL_FRM_XuanZheJiGouClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.司机管理.BLL_FRM_XuanZheJiGou.BLL_FRM_XuanZheJiGou>, WCF物流管理系统_Client.BLL物流管理系统.司机管理.BLL_FRM_XuanZheJiGou.BLL_FRM_XuanZheJiGou {
        
        public BLL_FRM_XuanZheJiGouClient() {
        }
        
        public BLL_FRM_XuanZheJiGouClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BLL_FRM_XuanZheJiGouClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BLL_FRM_XuanZheJiGouClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BLL_FRM_XuanZheJiGouClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_XuanZheJiGou_Load_ChaXunJiGouZuZhi(int 机构组织ID) {
            return base.Channel.FRM_XuanZheJiGou_Load_ChaXunJiGouZuZhi(机构组织ID);
        }
    }
}
