//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.司机管理.BLL_FRM_SiJiGuanLi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.司机管理.BLL_FRM_SiJiGuanLi.BLL_FRM_SiJiGuanLi")]
    public interface BLL_FRM_SiJiGuanLi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BLL_FRM_SiJiGuanLi/FRM_SiJiGuanLi_Load_ChaXunSiJiXinXi", ReplyAction="http://tempuri.org/BLL_FRM_SiJiGuanLi/FRM_SiJiGuanLi_Load_ChaXunSiJiXinXiResponse" +
            "")]
        System.Data.DataSet FRM_SiJiGuanLi_Load_ChaXunSiJiXinXi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BLL_FRM_SiJiGuanLi/tsbShanChu_Delete_Click_ShanChu", ReplyAction="http://tempuri.org/BLL_FRM_SiJiGuanLi/tsbShanChu_Delete_Click_ShanChuResponse")]
        bool tsbShanChu_Delete_Click_ShanChu(int 司机ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BLL_FRM_SiJiGuanLiChannel : WCF物流管理系统_Client.BLL物流管理系统.司机管理.BLL_FRM_SiJiGuanLi.BLL_FRM_SiJiGuanLi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BLL_FRM_SiJiGuanLiClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.司机管理.BLL_FRM_SiJiGuanLi.BLL_FRM_SiJiGuanLi>, WCF物流管理系统_Client.BLL物流管理系统.司机管理.BLL_FRM_SiJiGuanLi.BLL_FRM_SiJiGuanLi {
        
        public BLL_FRM_SiJiGuanLiClient() {
        }
        
        public BLL_FRM_SiJiGuanLiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BLL_FRM_SiJiGuanLiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BLL_FRM_SiJiGuanLiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BLL_FRM_SiJiGuanLiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_SiJiGuanLi_Load_ChaXunSiJiXinXi() {
            return base.Channel.FRM_SiJiGuanLi_Load_ChaXunSiJiXinXi();
        }
        
        public bool tsbShanChu_Delete_Click_ShanChu(int 司机ID) {
            return base.Channel.tsbShanChu_Delete_Click_ShanChu(司机ID);
        }
    }
}
