//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.Login {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.Login.Login")]
    public interface Login {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login/frmLogin_SelectYongHuMing", ReplyAction="http://tempuri.org/Login/frmLogin_SelectYongHuMingResponse")]
        System.Data.DataSet frmLogin_SelectYongHuMing();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login/frmLogin_JudgeLogin", ReplyAction="http://tempuri.org/Login/frmLogin_JudgeLoginResponse")]
        System.Data.DataSet frmLogin_JudgeLogin(string YongHuMing, string MiMa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login/frmLogin_SelectYongHuID", ReplyAction="http://tempuri.org/Login/frmLogin_SelectYongHuIDResponse")]
        System.Data.DataSet frmLogin_SelectYongHuID(string YongHuMing, string MiMa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login/frmLogin_SelectYuanGongByYongHuID", ReplyAction="http://tempuri.org/Login/frmLogin_SelectYuanGongByYongHuIDResponse")]
        System.Data.DataSet frmLogin_SelectYuanGongByYongHuID(int 用户ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login/FaSongYouJian", ReplyAction="http://tempuri.org/Login/FaSongYouJianResponse")]
        void FaSongYouJian();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginChannel : WCF物流管理系统_Client.BLL物流管理系统.Login.Login, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.Login.Login>, WCF物流管理系统_Client.BLL物流管理系统.Login.Login {
        
        public LoginClient() {
        }
        
        public LoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet frmLogin_SelectYongHuMing() {
            return base.Channel.frmLogin_SelectYongHuMing();
        }
        
        public System.Data.DataSet frmLogin_JudgeLogin(string YongHuMing, string MiMa) {
            return base.Channel.frmLogin_JudgeLogin(YongHuMing, MiMa);
        }
        
        public System.Data.DataSet frmLogin_SelectYongHuID(string YongHuMing, string MiMa) {
            return base.Channel.frmLogin_SelectYongHuID(YongHuMing, MiMa);
        }
        
        public System.Data.DataSet frmLogin_SelectYuanGongByYongHuID(int 用户ID) {
            return base.Channel.frmLogin_SelectYuanGongByYongHuID(用户ID);
        }
        
        public void FaSongYouJian() {
            base.Channel.FaSongYouJian();
        }
    }
}
