//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.线路管理.FRM_XianLuGuanLi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.线路管理.FRM_XianLuGuanLi.FRM_XianLuGuanLi")]
    public interface FRM_XianLuGuanLi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_XianLuGuanLi/FRM_XianLuGuanLi_Load_ChaXunXianLuXinXi", ReplyAction="http://tempuri.org/FRM_XianLuGuanLi/FRM_XianLuGuanLi_Load_ChaXunXianLuXinXiRespon" +
            "se")]
        System.Data.DataSet FRM_XianLuGuanLi_Load_ChaXunXianLuXinXi(string 线路名称);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_XianLuGuanLi/dgvXianLuXinXi_CellClick_ChaXunXianLuXiangXiX" +
            "inXi", ReplyAction="http://tempuri.org/FRM_XianLuGuanLi/dgvXianLuXinXi_CellClick_ChaXunXianLuXiangXiX" +
            "inXiResponse")]
        System.Data.DataSet dgvXianLuXinXi_CellClick_ChaXunXianLuXiangXiXinXi(string 线路ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_XianLuGuanLi/FRM_XianLuGuanLi_Load_ChaXunQuanBuXianLu", ReplyAction="http://tempuri.org/FRM_XianLuGuanLi/FRM_XianLuGuanLi_Load_ChaXunQuanBuXianLuRespo" +
            "nse")]
        System.Data.DataSet FRM_XianLuGuanLi_Load_ChaXunQuanBuXianLu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_XianLuGuanLi/tsbShangChu_Delete_Click_ShanChuXianLu", ReplyAction="http://tempuri.org/FRM_XianLuGuanLi/tsbShangChu_Delete_Click_ShanChuXianLuRespons" +
            "e")]
        int tsbShangChu_Delete_Click_ShanChuXianLu(string 线路ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_XianLuGuanLi/FRM_XianLuGuanLi_Load_DuoTiaoJianChaXunXianLu" +
            "", ReplyAction="http://tempuri.org/FRM_XianLuGuanLi/FRM_XianLuGuanLi_Load_DuoTiaoJianChaXunXianLu" +
            "Response")]
        System.Data.DataSet FRM_XianLuGuanLi_Load_DuoTiaoJianChaXunXianLu(string 线路名称, string 助记码);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_XianLuGuanLiChannel : WCF物流管理系统_Client.BLL物流管理系统.线路管理.FRM_XianLuGuanLi.FRM_XianLuGuanLi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_XianLuGuanLiClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.线路管理.FRM_XianLuGuanLi.FRM_XianLuGuanLi>, WCF物流管理系统_Client.BLL物流管理系统.线路管理.FRM_XianLuGuanLi.FRM_XianLuGuanLi {
        
        public FRM_XianLuGuanLiClient() {
        }
        
        public FRM_XianLuGuanLiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_XianLuGuanLiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_XianLuGuanLiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_XianLuGuanLiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_XianLuGuanLi_Load_ChaXunXianLuXinXi(string 线路名称) {
            return base.Channel.FRM_XianLuGuanLi_Load_ChaXunXianLuXinXi(线路名称);
        }
        
        public System.Data.DataSet dgvXianLuXinXi_CellClick_ChaXunXianLuXiangXiXinXi(string 线路ID) {
            return base.Channel.dgvXianLuXinXi_CellClick_ChaXunXianLuXiangXiXinXi(线路ID);
        }
        
        public System.Data.DataSet FRM_XianLuGuanLi_Load_ChaXunQuanBuXianLu() {
            return base.Channel.FRM_XianLuGuanLi_Load_ChaXunQuanBuXianLu();
        }
        
        public int tsbShangChu_Delete_Click_ShanChuXianLu(string 线路ID) {
            return base.Channel.tsbShangChu_Delete_Click_ShanChuXianLu(线路ID);
        }
        
        public System.Data.DataSet FRM_XianLuGuanLi_Load_DuoTiaoJianChaXunXianLu(string 线路名称, string 助记码) {
            return base.Channel.FRM_XianLuGuanLi_Load_DuoTiaoJianChaXunXianLu(线路名称, 助记码);
        }
    }
}
