//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.出车登记.FRM_DaoDaDengJi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.出车登记.FRM_DaoDaDengJi.FRM_DaoDaDengJi")]
    public interface FRM_DaoDaDengJi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_DaoDaDengJi/btnDaoDa_Click_ChaXunFaCheDian", ReplyAction="http://tempuri.org/FRM_DaoDaDengJi/btnDaoDa_Click_ChaXunFaCheDianResponse")]
        int btnDaoDa_Click_ChaXunFaCheDian(string 车辆ID, string 到达网点ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_DaoDaDengJi/btnDaoDa_Click_ChaRuGenZongBiao", ReplyAction="http://tempuri.org/FRM_DaoDaDengJi/btnDaoDa_Click_ChaRuGenZongBiaoResponse")]
        int btnDaoDa_Click_ChaRuGenZongBiao(string 到达网点ID, string 配载发车单ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_DaoDaDengJi/ShiJianDuanFaSongYouJian", ReplyAction="http://tempuri.org/FRM_DaoDaDengJi/ShiJianDuanFaSongYouJianResponse")]
        System.Data.DataTable ShiJianDuanFaSongYouJian();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_DaoDaDengJi/FaYouJianHouGengXinWuLiuGenZong", ReplyAction="http://tempuri.org/FRM_DaoDaDengJi/FaYouJianHouGengXinWuLiuGenZongResponse")]
        int FaYouJianHouGengXinWuLiuGenZong(string 物流跟踪ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_DaoDaDengJi/FRM_DaoDaDengJi_IDChaXunCheLiangZhuangTai", ReplyAction="http://tempuri.org/FRM_DaoDaDengJi/FRM_DaoDaDengJi_IDChaXunCheLiangZhuangTaiRespo" +
            "nse")]
        System.Data.DataSet FRM_DaoDaDengJi_IDChaXunCheLiangZhuangTai(int 车辆ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_DaoDaDengJi/FRM_DaoDaDengJi_Load_ChaXunQuanBuCheLiang", ReplyAction="http://tempuri.org/FRM_DaoDaDengJi/FRM_DaoDaDengJi_Load_ChaXunQuanBuCheLiangRespo" +
            "nse")]
        System.Data.DataSet FRM_DaoDaDengJi_Load_ChaXunQuanBuCheLiang();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_DaoDaDengJi/FRM_DaoDaDengJi_Load_ChaXunWangDian", ReplyAction="http://tempuri.org/FRM_DaoDaDengJi/FRM_DaoDaDengJi_Load_ChaXunWangDianResponse")]
        System.Data.DataSet FRM_DaoDaDengJi_Load_ChaXunWangDian();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_DaoDaDengJi/FRM_DaoDaDengJi_Load_ChaXunZhuangTai", ReplyAction="http://tempuri.org/FRM_DaoDaDengJi/FRM_DaoDaDengJi_Load_ChaXunZhuangTaiResponse")]
        System.Data.DataSet FRM_DaoDaDengJi_Load_ChaXunZhuangTai();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_DaoDaDengJi/pb_MouseClick_ChaXunMingXi", ReplyAction="http://tempuri.org/FRM_DaoDaDengJi/pb_MouseClick_ChaXunMingXiResponse")]
        System.Data.DataSet pb_MouseClick_ChaXunMingXi(int 配载发车单ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_DaoDaDengJiChannel : WCF物流管理系统_Client.BLL物流管理系统.出车登记.FRM_DaoDaDengJi.FRM_DaoDaDengJi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_DaoDaDengJiClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.出车登记.FRM_DaoDaDengJi.FRM_DaoDaDengJi>, WCF物流管理系统_Client.BLL物流管理系统.出车登记.FRM_DaoDaDengJi.FRM_DaoDaDengJi {
        
        public FRM_DaoDaDengJiClient() {
        }
        
        public FRM_DaoDaDengJiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_DaoDaDengJiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_DaoDaDengJiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_DaoDaDengJiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int btnDaoDa_Click_ChaXunFaCheDian(string 车辆ID, string 到达网点ID) {
            return base.Channel.btnDaoDa_Click_ChaXunFaCheDian(车辆ID, 到达网点ID);
        }
        
        public int btnDaoDa_Click_ChaRuGenZongBiao(string 到达网点ID, string 配载发车单ID) {
            return base.Channel.btnDaoDa_Click_ChaRuGenZongBiao(到达网点ID, 配载发车单ID);
        }
        
        public System.Data.DataTable ShiJianDuanFaSongYouJian() {
            return base.Channel.ShiJianDuanFaSongYouJian();
        }
        
        public int FaYouJianHouGengXinWuLiuGenZong(string 物流跟踪ID) {
            return base.Channel.FaYouJianHouGengXinWuLiuGenZong(物流跟踪ID);
        }
        
        public System.Data.DataSet FRM_DaoDaDengJi_IDChaXunCheLiangZhuangTai(int 车辆ID) {
            return base.Channel.FRM_DaoDaDengJi_IDChaXunCheLiangZhuangTai(车辆ID);
        }
        
        public System.Data.DataSet FRM_DaoDaDengJi_Load_ChaXunQuanBuCheLiang() {
            return base.Channel.FRM_DaoDaDengJi_Load_ChaXunQuanBuCheLiang();
        }
        
        public System.Data.DataSet FRM_DaoDaDengJi_Load_ChaXunWangDian() {
            return base.Channel.FRM_DaoDaDengJi_Load_ChaXunWangDian();
        }
        
        public System.Data.DataSet FRM_DaoDaDengJi_Load_ChaXunZhuangTai() {
            return base.Channel.FRM_DaoDaDengJi_Load_ChaXunZhuangTai();
        }
        
        public System.Data.DataSet pb_MouseClick_ChaXunMingXi(int 配载发车单ID) {
            return base.Channel.pb_MouseClick_ChaXunMingXi(配载发车单ID);
        }
    }
}
