//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.订单管理.DingDanGuanLi_Insert {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.订单管理.DingDanGuanLi_Insert.DingDanGuanLi_Insert")]
    public interface DingDanGuanLi_Insert {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi_Insert/frmDingDanGuanLi_Insert_SelectHuodanhao", ReplyAction="http://tempuri.org/DingDanGuanLi_Insert/frmDingDanGuanLi_Insert_SelectHuodanhaoRe" +
            "sponse")]
        System.Data.DataSet frmDingDanGuanLi_Insert_SelectHuodanhao();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi_Insert/frmDingDanGuanLi_Insert_SelectWangDian", ReplyAction="http://tempuri.org/DingDanGuanLi_Insert/frmDingDanGuanLi_Insert_SelectWangDianRes" +
            "ponse")]
        System.Data.DataSet frmDingDanGuanLi_Insert_SelectWangDian();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi_Insert/frmDingDanGuanLi_Insert_SelectYuanGong", ReplyAction="http://tempuri.org/DingDanGuanLi_Insert/frmDingDanGuanLi_Insert_SelectYuanGongRes" +
            "ponse")]
        System.Data.DataSet frmDingDanGuanLi_Insert_SelectYuanGong();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi_Insert/frmDingDanGuanLi_Insert_SelectKeHu", ReplyAction="http://tempuri.org/DingDanGuanLi_Insert/frmDingDanGuanLi_Insert_SelectKeHuRespons" +
            "e")]
        System.Data.DataSet frmDingDanGuanLi_Insert_SelectKeHu(string 客户全称);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi_Insert/frmDingDanGuanLi_Insert_SelectJiFeiGongSh" +
            "i", ReplyAction="http://tempuri.org/DingDanGuanLi_Insert/frmDingDanGuanLi_Insert_SelectJiFeiGongSh" +
            "iResponse")]
        System.Data.DataSet frmDingDanGuanLi_Insert_SelectJiFeiGongShi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi_Insert/frmDingDanGuanLi_Insert_SelectJieSuanFang" +
            "Shi", ReplyAction="http://tempuri.org/DingDanGuanLi_Insert/frmDingDanGuanLi_Insert_SelectJieSuanFang" +
            "ShiResponse")]
        System.Data.DataSet frmDingDanGuanLi_Insert_SelectJieSuanFangShi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi_Insert/frmDingDanGuanLi_Insert_SelectCboLanShouZ" +
            "huangTai", ReplyAction="http://tempuri.org/DingDanGuanLi_Insert/frmDingDanGuanLi_Insert_SelectCboLanShouZ" +
            "huangTaiResponse")]
        System.Data.DataSet frmDingDanGuanLi_Insert_SelectCboLanShouZhuangTai();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi_Insert/frmDingDanGuanLi_Insert_SelectHuoWu", ReplyAction="http://tempuri.org/DingDanGuanLi_Insert/frmDingDanGuanLi_Insert_SelectHuoWuRespon" +
            "se")]
        System.Data.DataSet frmDingDanGuanLi_Insert_SelectHuoWu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi_Insert/btnBaoCun_Click_InsertDanJu", ReplyAction="http://tempuri.org/DingDanGuanLi_Insert/btnBaoCun_Click_InsertDanJuResponse")]
        int btnBaoCun_Click_InsertDanJu(
                    string 单据编号, 
                    System.DateTime 接单时间, 
                    int 业务员_员工ID, 
                    System.DateTime 要求送达时间, 
                    int 托运方ID, 
                    string 提单号, 
                    int 收货方ID, 
                    string 寄件地址, 
                    string 收货地址, 
                    int 结算方式ID, 
                    decimal 运费总价, 
                    string 备注, 
                    int 制单人_员工ID, 
                    int 修单人_员工ID, 
                    int 寄件网点ID, 
                    int 收货网点ID, 
                    int 货物揽收状态ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi_Insert/btnBaoCun_Click_InsertMingXi", ReplyAction="http://tempuri.org/DingDanGuanLi_Insert/btnBaoCun_Click_InsertMingXiResponse")]
        int btnBaoCun_Click_InsertMingXi(int 货物ID, decimal 数量, int 计费公式ID, decimal 运费单价, bool 揽收否, int 货运单ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi_Insert/btnBaoCun_Click_SelectZuiDaDanHao", ReplyAction="http://tempuri.org/DingDanGuanLi_Insert/btnBaoCun_Click_SelectZuiDaDanHaoResponse" +
            "")]
        int btnBaoCun_Click_SelectZuiDaDanHao();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DingDanGuanLi_InsertChannel : WCF物流管理系统_Client.BLL物流管理系统.订单管理.DingDanGuanLi_Insert.DingDanGuanLi_Insert, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DingDanGuanLi_InsertClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.订单管理.DingDanGuanLi_Insert.DingDanGuanLi_Insert>, WCF物流管理系统_Client.BLL物流管理系统.订单管理.DingDanGuanLi_Insert.DingDanGuanLi_Insert {
        
        public DingDanGuanLi_InsertClient() {
        }
        
        public DingDanGuanLi_InsertClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DingDanGuanLi_InsertClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DingDanGuanLi_InsertClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DingDanGuanLi_InsertClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet frmDingDanGuanLi_Insert_SelectHuodanhao() {
            return base.Channel.frmDingDanGuanLi_Insert_SelectHuodanhao();
        }
        
        public System.Data.DataSet frmDingDanGuanLi_Insert_SelectWangDian() {
            return base.Channel.frmDingDanGuanLi_Insert_SelectWangDian();
        }
        
        public System.Data.DataSet frmDingDanGuanLi_Insert_SelectYuanGong() {
            return base.Channel.frmDingDanGuanLi_Insert_SelectYuanGong();
        }
        
        public System.Data.DataSet frmDingDanGuanLi_Insert_SelectKeHu(string 客户全称) {
            return base.Channel.frmDingDanGuanLi_Insert_SelectKeHu(客户全称);
        }
        
        public System.Data.DataSet frmDingDanGuanLi_Insert_SelectJiFeiGongShi() {
            return base.Channel.frmDingDanGuanLi_Insert_SelectJiFeiGongShi();
        }
        
        public System.Data.DataSet frmDingDanGuanLi_Insert_SelectJieSuanFangShi() {
            return base.Channel.frmDingDanGuanLi_Insert_SelectJieSuanFangShi();
        }
        
        public System.Data.DataSet frmDingDanGuanLi_Insert_SelectCboLanShouZhuangTai() {
            return base.Channel.frmDingDanGuanLi_Insert_SelectCboLanShouZhuangTai();
        }
        
        public System.Data.DataSet frmDingDanGuanLi_Insert_SelectHuoWu() {
            return base.Channel.frmDingDanGuanLi_Insert_SelectHuoWu();
        }
        
        public int btnBaoCun_Click_InsertDanJu(
                    string 单据编号, 
                    System.DateTime 接单时间, 
                    int 业务员_员工ID, 
                    System.DateTime 要求送达时间, 
                    int 托运方ID, 
                    string 提单号, 
                    int 收货方ID, 
                    string 寄件地址, 
                    string 收货地址, 
                    int 结算方式ID, 
                    decimal 运费总价, 
                    string 备注, 
                    int 制单人_员工ID, 
                    int 修单人_员工ID, 
                    int 寄件网点ID, 
                    int 收货网点ID, 
                    int 货物揽收状态ID) {
            return base.Channel.btnBaoCun_Click_InsertDanJu(单据编号, 接单时间, 业务员_员工ID, 要求送达时间, 托运方ID, 提单号, 收货方ID, 寄件地址, 收货地址, 结算方式ID, 运费总价, 备注, 制单人_员工ID, 修单人_员工ID, 寄件网点ID, 收货网点ID, 货物揽收状态ID);
        }
        
        public int btnBaoCun_Click_InsertMingXi(int 货物ID, decimal 数量, int 计费公式ID, decimal 运费单价, bool 揽收否, int 货运单ID) {
            return base.Channel.btnBaoCun_Click_InsertMingXi(货物ID, 数量, 计费公式ID, 运费单价, 揽收否, 货运单ID);
        }
        
        public int btnBaoCun_Click_SelectZuiDaDanHao() {
            return base.Channel.btnBaoCun_Click_SelectZuiDaDanHao();
        }
    }
}
