//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.报表统计.FRM_DingDanBaoBiao {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.报表统计.FRM_DingDanBaoBiao.FRM_DingDanBaoBiao")]
    public interface FRM_DingDanBaoBiao {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_DingDanBaoBiao/FRM_DingDanBaoBiao_Load_ChaXunDingDan", ReplyAction="http://tempuri.org/FRM_DingDanBaoBiao/FRM_DingDanBaoBiao_Load_ChaXunDingDanRespon" +
            "se")]
        System.Data.DataSet FRM_DingDanBaoBiao_Load_ChaXunDingDan(string 货运单ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_DingDanBaoBiao/FRM_DingDanBaoBiao_Load_ChaXunMingXi", ReplyAction="http://tempuri.org/FRM_DingDanBaoBiao/FRM_DingDanBaoBiao_Load_ChaXunMingXiRespons" +
            "e")]
        System.Data.DataSet FRM_DingDanBaoBiao_Load_ChaXunMingXi(string 货运单ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_DingDanBaoBiaoChannel : WCF物流管理系统_Client.BLL物流管理系统.报表统计.FRM_DingDanBaoBiao.FRM_DingDanBaoBiao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_DingDanBaoBiaoClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.报表统计.FRM_DingDanBaoBiao.FRM_DingDanBaoBiao>, WCF物流管理系统_Client.BLL物流管理系统.报表统计.FRM_DingDanBaoBiao.FRM_DingDanBaoBiao {
        
        public FRM_DingDanBaoBiaoClient() {
        }
        
        public FRM_DingDanBaoBiaoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_DingDanBaoBiaoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_DingDanBaoBiaoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_DingDanBaoBiaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_DingDanBaoBiao_Load_ChaXunDingDan(string 货运单ID) {
            return base.Channel.FRM_DingDanBaoBiao_Load_ChaXunDingDan(货运单ID);
        }
        
        public System.Data.DataSet FRM_DingDanBaoBiao_Load_ChaXunMingXi(string 货运单ID) {
            return base.Channel.FRM_DingDanBaoBiao_Load_ChaXunMingXi(货运单ID);
        }
    }
}
