//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.线路管理.FRM_XianLuGuanLi_WangDianGuanLi_Insert {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.线路管理.FRM_XianLuGuanLi_WangDianGuanLi_Insert.FRM_XianLuGuanLi_WangDianGu" +
        "anLi_Insert")]
    public interface FRM_XianLuGuanLi_WangDianGuanLi_Insert {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_XianLuGuanLi_WangDianGuanLi_Insert/btnBaoCun_Click_ChaRuWa" +
            "ngDianXinXi", ReplyAction="http://tempuri.org/FRM_XianLuGuanLi_WangDianGuanLi_Insert/btnBaoCun_Click_ChaRuWa" +
            "ngDianXinXiResponse")]
        System.Data.DataSet btnBaoCun_Click_ChaRuWangDianXinXi(string 网点名称, string 停用否);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_XianLuGuanLi_WangDianGuanLi_Insert/FRM_XianLuGuanLi_WangDi" +
            "anGuanLi_Insert_Load_ChaXunWangDianXinXi", ReplyAction="http://tempuri.org/FRM_XianLuGuanLi_WangDianGuanLi_Insert/FRM_XianLuGuanLi_WangDi" +
            "anGuanLi_Insert_Load_ChaXunWangDianXinXiResponse")]
        System.Data.DataSet FRM_XianLuGuanLi_WangDianGuanLi_Insert_Load_ChaXunWangDianXinXi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_XianLuGuanLi_WangDianGuanLi_Insert/btnBaoCun_Click_ChaRuWa" +
            "ngDianXinXi_ChaRuXiangLinWangDian", ReplyAction="http://tempuri.org/FRM_XianLuGuanLi_WangDianGuanLi_Insert/btnBaoCun_Click_ChaRuWa" +
            "ngDianXinXi_ChaRuXiangLinWangDianResponse")]
        System.Data.DataSet btnBaoCun_Click_ChaRuWangDianXinXi_ChaRuXiangLinWangDian(int 网点ID, int 邻居网点ID, decimal 距离);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_XianLuGuanLi_WangDianGuanLi_InsertChannel : WCF物流管理系统_Client.BLL物流管理系统.线路管理.FRM_XianLuGuanLi_WangDianGuanLi_Insert.FRM_XianLuGuanLi_WangDianGuanLi_Insert, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_XianLuGuanLi_WangDianGuanLi_InsertClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.线路管理.FRM_XianLuGuanLi_WangDianGuanLi_Insert.FRM_XianLuGuanLi_WangDianGuanLi_Insert>, WCF物流管理系统_Client.BLL物流管理系统.线路管理.FRM_XianLuGuanLi_WangDianGuanLi_Insert.FRM_XianLuGuanLi_WangDianGuanLi_Insert {
        
        public FRM_XianLuGuanLi_WangDianGuanLi_InsertClient() {
        }
        
        public FRM_XianLuGuanLi_WangDianGuanLi_InsertClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_XianLuGuanLi_WangDianGuanLi_InsertClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_XianLuGuanLi_WangDianGuanLi_InsertClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_XianLuGuanLi_WangDianGuanLi_InsertClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet btnBaoCun_Click_ChaRuWangDianXinXi(string 网点名称, string 停用否) {
            return base.Channel.btnBaoCun_Click_ChaRuWangDianXinXi(网点名称, 停用否);
        }
        
        public System.Data.DataSet FRM_XianLuGuanLi_WangDianGuanLi_Insert_Load_ChaXunWangDianXinXi() {
            return base.Channel.FRM_XianLuGuanLi_WangDianGuanLi_Insert_Load_ChaXunWangDianXinXi();
        }
        
        public System.Data.DataSet btnBaoCun_Click_ChaRuWangDianXinXi_ChaRuXiangLinWangDian(int 网点ID, int 邻居网点ID, decimal 距离) {
            return base.Channel.btnBaoCun_Click_ChaRuWangDianXinXi_ChaRuXiangLinWangDian(网点ID, 邻居网点ID, 距离);
        }
    }
}
