//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_QuanXianZu {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.用户权限管理.BLL_QuanXianZu.BLL_QuanXianZu")]
    public interface BLL_QuanXianZu {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BLL_QuanXianZu/FRM_QuanXianZu_Load_ChaXunQuanXianZu", ReplyAction="http://tempuri.org/BLL_QuanXianZu/FRM_QuanXianZu_Load_ChaXunQuanXianZuResponse")]
        System.Data.DataSet FRM_QuanXianZu_Load_ChaXunQuanXianZu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BLL_QuanXianZu/FRM_QuanXianZu_dgvAuthGroup_CellClick_ChaXunMoK" +
            "uai", ReplyAction="http://tempuri.org/BLL_QuanXianZu/FRM_QuanXianZu_dgvAuthGroup_CellClick_ChaXunMoK" +
            "uaiResponse")]
        System.Data.DataSet FRM_QuanXianZu_dgvAuthGroup_CellClick_ChaXunMoKuai(int 权限组ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BLL_QuanXianZu/FRM_QuanXianZu_btnDelQuanXianZu_Click", ReplyAction="http://tempuri.org/BLL_QuanXianZu/FRM_QuanXianZu_btnDelQuanXianZu_ClickResponse")]
        int FRM_QuanXianZu_btnDelQuanXianZu_Click(int 权限组ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BLL_QuanXianZuChannel : WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_QuanXianZu.BLL_QuanXianZu, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BLL_QuanXianZuClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_QuanXianZu.BLL_QuanXianZu>, WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_QuanXianZu.BLL_QuanXianZu {
        
        public BLL_QuanXianZuClient() {
        }
        
        public BLL_QuanXianZuClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BLL_QuanXianZuClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BLL_QuanXianZuClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BLL_QuanXianZuClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_QuanXianZu_Load_ChaXunQuanXianZu() {
            return base.Channel.FRM_QuanXianZu_Load_ChaXunQuanXianZu();
        }
        
        public System.Data.DataSet FRM_QuanXianZu_dgvAuthGroup_CellClick_ChaXunMoKuai(int 权限组ID) {
            return base.Channel.FRM_QuanXianZu_dgvAuthGroup_CellClick_ChaXunMoKuai(权限组ID);
        }
        
        public int FRM_QuanXianZu_btnDelQuanXianZu_Click(int 权限组ID) {
            return base.Channel.FRM_QuanXianZu_btnDelQuanXianZu_Click(权限组ID);
        }
    }
}
