//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_QuanXianZu_Insert {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.用户权限管理.BLL_QuanXianZu_Insert.BLL_QuanXianZu_Insert")]
    public interface BLL_QuanXianZu_Insert {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BLL_QuanXianZu_Insert/FRM_QuanXianZu_Insert_Load_ChaXunMoKuai", ReplyAction="http://tempuri.org/BLL_QuanXianZu_Insert/FRM_QuanXianZu_Insert_Load_ChaXunMoKuaiR" +
            "esponse")]
        System.Data.DataSet FRM_QuanXianZu_Insert_Load_ChaXunMoKuai();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BLL_QuanXianZu_Insert/FRM_QuanXianZu_Insert_btnQueDing_Click_T" +
            "ianJiaQuanXianZu", ReplyAction="http://tempuri.org/BLL_QuanXianZu_Insert/FRM_QuanXianZu_Insert_btnQueDing_Click_T" +
            "ianJiaQuanXianZuResponse")]
        int FRM_QuanXianZu_Insert_btnQueDing_Click_TianJiaQuanXianZu(int[] 模块ID, string 权限组名称);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BLL_QuanXianZu_InsertChannel : WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_QuanXianZu_Insert.BLL_QuanXianZu_Insert, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BLL_QuanXianZu_InsertClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_QuanXianZu_Insert.BLL_QuanXianZu_Insert>, WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_QuanXianZu_Insert.BLL_QuanXianZu_Insert {
        
        public BLL_QuanXianZu_InsertClient() {
        }
        
        public BLL_QuanXianZu_InsertClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BLL_QuanXianZu_InsertClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BLL_QuanXianZu_InsertClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BLL_QuanXianZu_InsertClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_QuanXianZu_Insert_Load_ChaXunMoKuai() {
            return base.Channel.FRM_QuanXianZu_Insert_Load_ChaXunMoKuai();
        }
        
        public int FRM_QuanXianZu_Insert_btnQueDing_Click_TianJiaQuanXianZu(int[] 模块ID, string 权限组名称) {
            return base.Channel.FRM_QuanXianZu_Insert_btnQueDing_Click_TianJiaQuanXianZu(模块ID, 权限组名称);
        }
    }
}
