//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.订单管理.DingDanGuanLi_Update {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.订单管理.DingDanGuanLi_Update.DingDanGuanLi_Update")]
    public interface DingDanGuanLi_Update {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi_Update/frmDingDanGuanLi_Update_SelectWangDian", ReplyAction="http://tempuri.org/DingDanGuanLi_Update/frmDingDanGuanLi_Update_SelectWangDianRes" +
            "ponse")]
        System.Data.DataSet frmDingDanGuanLi_Update_SelectWangDian();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi_Update/frmDingDanGuanLi_Update_SelectYuanGong", ReplyAction="http://tempuri.org/DingDanGuanLi_Update/frmDingDanGuanLi_Update_SelectYuanGongRes" +
            "ponse")]
        System.Data.DataSet frmDingDanGuanLi_Update_SelectYuanGong();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi_Update/frmDingDanGuanLi_Update_SelectKeHu", ReplyAction="http://tempuri.org/DingDanGuanLi_Update/frmDingDanGuanLi_Update_SelectKeHuRespons" +
            "e")]
        System.Data.DataSet frmDingDanGuanLi_Update_SelectKeHu(string 客户名称);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi_Update/frmDingDanGuanLi_Update_SelectJiFeiGongSh" +
            "i", ReplyAction="http://tempuri.org/DingDanGuanLi_Update/frmDingDanGuanLi_Update_SelectJiFeiGongSh" +
            "iResponse")]
        System.Data.DataSet frmDingDanGuanLi_Update_SelectJiFeiGongShi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi_Update/frmDingDanGuanLi_Update_SelectJieSuanFang" +
            "Shi", ReplyAction="http://tempuri.org/DingDanGuanLi_Update/frmDingDanGuanLi_Update_SelectJieSuanFang" +
            "ShiResponse")]
        System.Data.DataSet frmDingDanGuanLi_Update_SelectJieSuanFangShi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi_Update/frmDingDanGuanLi_Update_SelectCboLanShouZ" +
            "huangTai", ReplyAction="http://tempuri.org/DingDanGuanLi_Update/frmDingDanGuanLi_Update_SelectCboLanShouZ" +
            "huangTaiResponse")]
        System.Data.DataSet frmDingDanGuanLi_Update_SelectCboLanShouZhuangTai();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi_Update/frmDingDanGuanLi_Update_SelectHuoWu", ReplyAction="http://tempuri.org/DingDanGuanLi_Update/frmDingDanGuanLi_Update_SelectHuoWuRespon" +
            "se")]
        System.Data.DataSet frmDingDanGuanLi_Update_SelectHuoWu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi_Update/frmDingDanGuanLi_Update_Load_SelectHuoYun" +
            "Dan", ReplyAction="http://tempuri.org/DingDanGuanLi_Update/frmDingDanGuanLi_Update_Load_SelectHuoYun" +
            "DanResponse")]
        System.Data.DataSet frmDingDanGuanLi_Update_Load_SelectHuoYunDan(int huoYunDanID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi_Update/frmDingDanGuanLi_Update_SelectHuoYunDanMi" +
            "ngXiByHuoYunDanID", ReplyAction="http://tempuri.org/DingDanGuanLi_Update/frmDingDanGuanLi_Update_SelectHuoYunDanMi" +
            "ngXiByHuoYunDanIDResponse")]
        System.Data.DataSet frmDingDanGuanLi_Update_SelectHuoYunDanMingXiByHuoYunDanID(int huoYunDanID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi_Update/btnBaoCun_Click_UpdateDanJu", ReplyAction="http://tempuri.org/DingDanGuanLi_Update/btnBaoCun_Click_UpdateDanJuResponse")]
        int btnBaoCun_Click_UpdateDanJu(
                    string 单据编号, 
                    System.DateTime 接单时间, 
                    int 业务员_员工ID, 
                    System.DateTime 要求送达时间, 
                    int 托运方ID, 
                    string 提单号, 
                    int 收货方ID, 
                    string 寄件地址, 
                    string 收货地址, 
                    int 结算方式ID, 
                    decimal 运费总价, 
                    string 备注, 
                    int 制单人_员工ID, 
                    int 修单人_员工ID, 
                    int 寄件网点ID, 
                    int 收货网点ID, 
                    int 货物揽收状态ID, 
                    int 货运单ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi_Update/btnBaoCun_Click_UpdateMingXi", ReplyAction="http://tempuri.org/DingDanGuanLi_Update/btnBaoCun_Click_UpdateMingXiResponse")]
        int btnBaoCun_Click_UpdateMingXi(int 货物ID, decimal 数量, int 计费公式ID, decimal 运费单价, bool 揽收否, int 货运单ID, int 货运单明细ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi_Update/btnBaoCun_Click_InsertDanJuMingXi", ReplyAction="http://tempuri.org/DingDanGuanLi_Update/btnBaoCun_Click_InsertDanJuMingXiResponse" +
            "")]
        int btnBaoCun_Click_InsertDanJuMingXi(int 货物ID, decimal 数量, int 计费公式ID, decimal 运费单价, bool 揽收否, int 货运单ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DingDanGuanLi_Update/btnBaoCun_Click_DeleteDanJuMingXi", ReplyAction="http://tempuri.org/DingDanGuanLi_Update/btnBaoCun_Click_DeleteDanJuMingXiResponse" +
            "")]
        int btnBaoCun_Click_DeleteDanJuMingXi(int 货运单明细ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DingDanGuanLi_UpdateChannel : WCF物流管理系统_Client.BLL物流管理系统.订单管理.DingDanGuanLi_Update.DingDanGuanLi_Update, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DingDanGuanLi_UpdateClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.订单管理.DingDanGuanLi_Update.DingDanGuanLi_Update>, WCF物流管理系统_Client.BLL物流管理系统.订单管理.DingDanGuanLi_Update.DingDanGuanLi_Update {
        
        public DingDanGuanLi_UpdateClient() {
        }
        
        public DingDanGuanLi_UpdateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DingDanGuanLi_UpdateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DingDanGuanLi_UpdateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DingDanGuanLi_UpdateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet frmDingDanGuanLi_Update_SelectWangDian() {
            return base.Channel.frmDingDanGuanLi_Update_SelectWangDian();
        }
        
        public System.Data.DataSet frmDingDanGuanLi_Update_SelectYuanGong() {
            return base.Channel.frmDingDanGuanLi_Update_SelectYuanGong();
        }
        
        public System.Data.DataSet frmDingDanGuanLi_Update_SelectKeHu(string 客户名称) {
            return base.Channel.frmDingDanGuanLi_Update_SelectKeHu(客户名称);
        }
        
        public System.Data.DataSet frmDingDanGuanLi_Update_SelectJiFeiGongShi() {
            return base.Channel.frmDingDanGuanLi_Update_SelectJiFeiGongShi();
        }
        
        public System.Data.DataSet frmDingDanGuanLi_Update_SelectJieSuanFangShi() {
            return base.Channel.frmDingDanGuanLi_Update_SelectJieSuanFangShi();
        }
        
        public System.Data.DataSet frmDingDanGuanLi_Update_SelectCboLanShouZhuangTai() {
            return base.Channel.frmDingDanGuanLi_Update_SelectCboLanShouZhuangTai();
        }
        
        public System.Data.DataSet frmDingDanGuanLi_Update_SelectHuoWu() {
            return base.Channel.frmDingDanGuanLi_Update_SelectHuoWu();
        }
        
        public System.Data.DataSet frmDingDanGuanLi_Update_Load_SelectHuoYunDan(int huoYunDanID) {
            return base.Channel.frmDingDanGuanLi_Update_Load_SelectHuoYunDan(huoYunDanID);
        }
        
        public System.Data.DataSet frmDingDanGuanLi_Update_SelectHuoYunDanMingXiByHuoYunDanID(int huoYunDanID) {
            return base.Channel.frmDingDanGuanLi_Update_SelectHuoYunDanMingXiByHuoYunDanID(huoYunDanID);
        }
        
        public int btnBaoCun_Click_UpdateDanJu(
                    string 单据编号, 
                    System.DateTime 接单时间, 
                    int 业务员_员工ID, 
                    System.DateTime 要求送达时间, 
                    int 托运方ID, 
                    string 提单号, 
                    int 收货方ID, 
                    string 寄件地址, 
                    string 收货地址, 
                    int 结算方式ID, 
                    decimal 运费总价, 
                    string 备注, 
                    int 制单人_员工ID, 
                    int 修单人_员工ID, 
                    int 寄件网点ID, 
                    int 收货网点ID, 
                    int 货物揽收状态ID, 
                    int 货运单ID) {
            return base.Channel.btnBaoCun_Click_UpdateDanJu(单据编号, 接单时间, 业务员_员工ID, 要求送达时间, 托运方ID, 提单号, 收货方ID, 寄件地址, 收货地址, 结算方式ID, 运费总价, 备注, 制单人_员工ID, 修单人_员工ID, 寄件网点ID, 收货网点ID, 货物揽收状态ID, 货运单ID);
        }
        
        public int btnBaoCun_Click_UpdateMingXi(int 货物ID, decimal 数量, int 计费公式ID, decimal 运费单价, bool 揽收否, int 货运单ID, int 货运单明细ID) {
            return base.Channel.btnBaoCun_Click_UpdateMingXi(货物ID, 数量, 计费公式ID, 运费单价, 揽收否, 货运单ID, 货运单明细ID);
        }
        
        public int btnBaoCun_Click_InsertDanJuMingXi(int 货物ID, decimal 数量, int 计费公式ID, decimal 运费单价, bool 揽收否, int 货运单ID) {
            return base.Channel.btnBaoCun_Click_InsertDanJuMingXi(货物ID, 数量, 计费公式ID, 运费单价, 揽收否, 货运单ID);
        }
        
        public int btnBaoCun_Click_DeleteDanJuMingXi(int 货运单明细ID) {
            return base.Channel.btnBaoCun_Click_DeleteDanJuMingXi(货运单明细ID);
        }
    }
}
