//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.配载发货.FRM_PeiZaiFaHuoFenBao_Update {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.配载发货.FRM_PeiZaiFaHuoFenBao_Update.FRM_PeiZaiFaHuoFenBao_Update")]
    public interface FRM_PeiZaiFaHuoFenBao_Update {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PeiZaiFaHuoFenBao_Update/FRM_PeiZaiFaHuoFenBao_Update_Load" +
            "_SelectDingDanMingXi", ReplyAction="http://tempuri.org/FRM_PeiZaiFaHuoFenBao_Update/FRM_PeiZaiFaHuoFenBao_Update_Load" +
            "_SelectDingDanMingXiResponse")]
        System.Data.DataSet FRM_PeiZaiFaHuoFenBao_Update_Load_SelectDingDanMingXi(int int货运单ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PeiZaiFaHuoFenBao_Update/dgvMingXi_SelectionChanged_Select" +
            "FenBao", ReplyAction="http://tempuri.org/FRM_PeiZaiFaHuoFenBao_Update/dgvMingXi_SelectionChanged_Select" +
            "FenBaoResponse")]
        System.Data.DataSet dgvMingXi_SelectionChanged_SelectFenBao(int 货运单明细ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PeiZaiFaHuoFenBao_Update/btnBaoCun_Update_Click_DeleteOldF" +
            "enBao", ReplyAction="http://tempuri.org/FRM_PeiZaiFaHuoFenBao_Update/btnBaoCun_Update_Click_DeleteOldF" +
            "enBaoResponse")]
        int btnBaoCun_Update_Click_DeleteOldFenBao(int 货运单明细ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PeiZaiFaHuoFenBao_Update/btnBaoCun_Update_Click_InsertNewF" +
            "enBao", ReplyAction="http://tempuri.org/FRM_PeiZaiFaHuoFenBao_Update/btnBaoCun_Update_Click_InsertNewF" +
            "enBaoResponse")]
        int btnBaoCun_Update_Click_InsertNewFenBao(int 货运单明细ID, decimal 分包数量);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_PeiZaiFaHuoFenBao_UpdateChannel : WCF物流管理系统_Client.BLL物流管理系统.配载发货.FRM_PeiZaiFaHuoFenBao_Update.FRM_PeiZaiFaHuoFenBao_Update, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_PeiZaiFaHuoFenBao_UpdateClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.配载发货.FRM_PeiZaiFaHuoFenBao_Update.FRM_PeiZaiFaHuoFenBao_Update>, WCF物流管理系统_Client.BLL物流管理系统.配载发货.FRM_PeiZaiFaHuoFenBao_Update.FRM_PeiZaiFaHuoFenBao_Update {
        
        public FRM_PeiZaiFaHuoFenBao_UpdateClient() {
        }
        
        public FRM_PeiZaiFaHuoFenBao_UpdateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_PeiZaiFaHuoFenBao_UpdateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_PeiZaiFaHuoFenBao_UpdateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_PeiZaiFaHuoFenBao_UpdateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_PeiZaiFaHuoFenBao_Update_Load_SelectDingDanMingXi(int int货运单ID) {
            return base.Channel.FRM_PeiZaiFaHuoFenBao_Update_Load_SelectDingDanMingXi(int货运单ID);
        }
        
        public System.Data.DataSet dgvMingXi_SelectionChanged_SelectFenBao(int 货运单明细ID) {
            return base.Channel.dgvMingXi_SelectionChanged_SelectFenBao(货运单明细ID);
        }
        
        public int btnBaoCun_Update_Click_DeleteOldFenBao(int 货运单明细ID) {
            return base.Channel.btnBaoCun_Update_Click_DeleteOldFenBao(货运单明细ID);
        }
        
        public int btnBaoCun_Update_Click_InsertNewFenBao(int 货运单明细ID, decimal 分包数量) {
            return base.Channel.btnBaoCun_Update_Click_InsertNewFenBao(货运单明细ID, 分包数量);
        }
    }
}
