//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.线路管理.FRM_XianLuGuanLi_WangDianGuanLi_Update {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.线路管理.FRM_XianLuGuanLi_WangDianGuanLi_Update.FRM_XianLuGuanLi_WangDianGu" +
        "anLi_Update")]
    public interface FRM_XianLuGuanLi_WangDianGuanLi_Update {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_XianLuGuanLi_WangDianGuanLi_Update/FRM_XianLuGuanLi_WangDi" +
            "anGuanLi_Update_Load_ChaXunWangDianXinXi", ReplyAction="http://tempuri.org/FRM_XianLuGuanLi_WangDianGuanLi_Update/FRM_XianLuGuanLi_WangDi" +
            "anGuanLi_Update_Load_ChaXunWangDianXinXiResponse")]
        System.Data.DataSet FRM_XianLuGuanLi_WangDianGuanLi_Update_Load_ChaXunWangDianXinXi(int 网点ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_XianLuGuanLi_WangDianGuanLi_Update/FRM_XianLuGuanLi_WangDi" +
            "anGuanLi_Update_Load_ChaXunWangDianXinXi_JvLi", ReplyAction="http://tempuri.org/FRM_XianLuGuanLi_WangDianGuanLi_Update/FRM_XianLuGuanLi_WangDi" +
            "anGuanLi_Update_Load_ChaXunWangDianXinXi_JvLiResponse")]
        System.Data.DataSet FRM_XianLuGuanLi_WangDianGuanLi_Update_Load_ChaXunWangDianXinXi_JvLi(int 网点ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_XianLuGuanLi_WangDianGuanLi_Update/btnBaoCun_Update_Click_" +
            "ShanChuXiangLinWangDian", ReplyAction="http://tempuri.org/FRM_XianLuGuanLi_WangDianGuanLi_Update/btnBaoCun_Update_Click_" +
            "ShanChuXiangLinWangDianResponse")]
        int btnBaoCun_Update_Click_ShanChuXiangLinWangDian(string 网点ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_XianLuGuanLi_WangDianGuanLi_Update/btnBaoCun_Update_Click_" +
            "XiuGaiWangDian", ReplyAction="http://tempuri.org/FRM_XianLuGuanLi_WangDianGuanLi_Update/btnBaoCun_Update_Click_" +
            "XiuGaiWangDianResponse")]
        int btnBaoCun_Update_Click_XiuGaiWangDian(string 网点名称, string 停用否, string 网点ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_XianLuGuanLi_WangDianGuanLi_UpdateChannel : WCF物流管理系统_Client.BLL物流管理系统.线路管理.FRM_XianLuGuanLi_WangDianGuanLi_Update.FRM_XianLuGuanLi_WangDianGuanLi_Update, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_XianLuGuanLi_WangDianGuanLi_UpdateClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.线路管理.FRM_XianLuGuanLi_WangDianGuanLi_Update.FRM_XianLuGuanLi_WangDianGuanLi_Update>, WCF物流管理系统_Client.BLL物流管理系统.线路管理.FRM_XianLuGuanLi_WangDianGuanLi_Update.FRM_XianLuGuanLi_WangDianGuanLi_Update {
        
        public FRM_XianLuGuanLi_WangDianGuanLi_UpdateClient() {
        }
        
        public FRM_XianLuGuanLi_WangDianGuanLi_UpdateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_XianLuGuanLi_WangDianGuanLi_UpdateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_XianLuGuanLi_WangDianGuanLi_UpdateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_XianLuGuanLi_WangDianGuanLi_UpdateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_XianLuGuanLi_WangDianGuanLi_Update_Load_ChaXunWangDianXinXi(int 网点ID) {
            return base.Channel.FRM_XianLuGuanLi_WangDianGuanLi_Update_Load_ChaXunWangDianXinXi(网点ID);
        }
        
        public System.Data.DataSet FRM_XianLuGuanLi_WangDianGuanLi_Update_Load_ChaXunWangDianXinXi_JvLi(int 网点ID) {
            return base.Channel.FRM_XianLuGuanLi_WangDianGuanLi_Update_Load_ChaXunWangDianXinXi_JvLi(网点ID);
        }
        
        public int btnBaoCun_Update_Click_ShanChuXiangLinWangDian(string 网点ID) {
            return base.Channel.btnBaoCun_Update_Click_ShanChuXiangLinWangDian(网点ID);
        }
        
        public int btnBaoCun_Update_Click_XiuGaiWangDian(string 网点名称, string 停用否, string 网点ID) {
            return base.Channel.btnBaoCun_Update_Click_XiuGaiWangDian(网点名称, 停用否, 网点ID);
        }
    }
}
