//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_authCheck {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.用户权限管理.BLL_authCheck.BLL_authCheck")]
    public interface BLL_authCheck {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BLL_authCheck/BLL_authCheck_checkAuthByType", ReplyAction="http://tempuri.org/BLL_authCheck/BLL_authCheck_checkAuthByTypeResponse")]
        bool BLL_authCheck_checkAuthByType(string 窗体名称, int 权限组ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BLL_authCheckChannel : WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_authCheck.BLL_authCheck, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BLL_authCheckClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_authCheck.BLL_authCheck>, WCF物流管理系统_Client.BLL物流管理系统.用户权限管理.BLL_authCheck.BLL_authCheck {
        
        public BLL_authCheckClient() {
        }
        
        public BLL_authCheckClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BLL_authCheckClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BLL_authCheckClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BLL_authCheckClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool BLL_authCheck_checkAuthByType(string 窗体名称, int 权限组ID) {
            return base.Channel.BLL_authCheck_checkAuthByType(窗体名称, 权限组ID);
        }
    }
}
