//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34003
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.车辆状态.FRM_CheLiangZhuangTai_Update {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.车辆状态.FRM_CheLiangZhuangTai_Update.FRM_CheLiangZhuangTai_Update")]
    public interface FRM_CheLiangZhuangTai_Update {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangZhuangTai_Update/FRM_CheLiangZhuangTai_Update_Load" +
            "_ChaXunCheDui", ReplyAction="http://tempuri.org/FRM_CheLiangZhuangTai_Update/FRM_CheLiangZhuangTai_Update_Load" +
            "_ChaXunCheDuiResponse")]
        System.Data.DataSet FRM_CheLiangZhuangTai_Update_Load_ChaXunCheDui();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangZhuangTai_Update/FRM_CheLiangZhuangTai_Update_Load" +
            "_ChaXunSiJi", ReplyAction="http://tempuri.org/FRM_CheLiangZhuangTai_Update/FRM_CheLiangZhuangTai_Update_Load" +
            "_ChaXunSiJiResponse")]
        System.Data.DataSet FRM_CheLiangZhuangTai_Update_Load_ChaXunSiJi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangZhuangTai_Update/FRM_CheLiangZhuangTai_Update_Load" +
            "_IDChaXunCheLiang", ReplyAction="http://tempuri.org/FRM_CheLiangZhuangTai_Update/FRM_CheLiangZhuangTai_Update_Load" +
            "_IDChaXunCheLiangResponse")]
        System.Data.DataSet FRM_CheLiangZhuangTai_Update_Load_IDChaXunCheLiang(string strCheLiangID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangZhuangTai_Update/btnBaoCun_Update_Click_XiuGaiCheL" +
            "iang", ReplyAction="http://tempuri.org/FRM_CheLiangZhuangTai_Update/btnBaoCun_Update_Click_XiuGaiCheL" +
            "iangResponse")]
        int btnBaoCun_Update_Click_XiuGaiCheLiang(string 车队ID, string 车牌号, string 行驶证号, string 保险证号, string 状态ID, string 发动机号, string 车架号, string 负责人_司机ID, string 紧急联系人_司机ID, byte[][] byteTuPian, string 车辆ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangZhuangTai_Update/FRM_CheLiangZhuangTai_Update_Load" +
            "_ChaXunTuPian", ReplyAction="http://tempuri.org/FRM_CheLiangZhuangTai_Update/FRM_CheLiangZhuangTai_Update_Load" +
            "_ChaXunTuPianResponse")]
        byte[][] FRM_CheLiangZhuangTai_Update_Load_ChaXunTuPian(string strLuJing);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_CheLiangZhuangTai_UpdateChannel : WCF物流管理系统_Client.BLL物流管理系统.车辆状态.FRM_CheLiangZhuangTai_Update.FRM_CheLiangZhuangTai_Update, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_CheLiangZhuangTai_UpdateClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.车辆状态.FRM_CheLiangZhuangTai_Update.FRM_CheLiangZhuangTai_Update>, WCF物流管理系统_Client.BLL物流管理系统.车辆状态.FRM_CheLiangZhuangTai_Update.FRM_CheLiangZhuangTai_Update {
        
        public FRM_CheLiangZhuangTai_UpdateClient() {
        }
        
        public FRM_CheLiangZhuangTai_UpdateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_CheLiangZhuangTai_UpdateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_CheLiangZhuangTai_UpdateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_CheLiangZhuangTai_UpdateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_CheLiangZhuangTai_Update_Load_ChaXunCheDui() {
            return base.Channel.FRM_CheLiangZhuangTai_Update_Load_ChaXunCheDui();
        }
        
        public System.Data.DataSet FRM_CheLiangZhuangTai_Update_Load_ChaXunSiJi() {
            return base.Channel.FRM_CheLiangZhuangTai_Update_Load_ChaXunSiJi();
        }
        
        public System.Data.DataSet FRM_CheLiangZhuangTai_Update_Load_IDChaXunCheLiang(string strCheLiangID) {
            return base.Channel.FRM_CheLiangZhuangTai_Update_Load_IDChaXunCheLiang(strCheLiangID);
        }
        
        public int btnBaoCun_Update_Click_XiuGaiCheLiang(string 车队ID, string 车牌号, string 行驶证号, string 保险证号, string 状态ID, string 发动机号, string 车架号, string 负责人_司机ID, string 紧急联系人_司机ID, byte[][] byteTuPian, string 车辆ID) {
            return base.Channel.btnBaoCun_Update_Click_XiuGaiCheLiang(车队ID, 车牌号, 行驶证号, 保险证号, 状态ID, 发动机号, 车架号, 负责人_司机ID, 紧急联系人_司机ID, byteTuPian, 车辆ID);
        }
        
        public byte[][] FRM_CheLiangZhuangTai_Update_Load_ChaXunTuPian(string strLuJing) {
            return base.Channel.FRM_CheLiangZhuangTai_Update_Load_ChaXunTuPian(strLuJing);
        }
    }
}
