//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.配载发货.PeiZaiFaHuoPeiZai_Insert {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.配载发货.PeiZaiFaHuoPeiZai_Insert.PeiZaiFaHuoPeiZai_Insert")]
    public interface PeiZaiFaHuoPeiZai_Insert {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PeiZaiFaHuoPeiZai_Insert/frmPeiZaiFaHuoPeiZai_Insert_SelectHuo" +
            "danhao", ReplyAction="http://tempuri.org/PeiZaiFaHuoPeiZai_Insert/frmPeiZaiFaHuoPeiZai_Insert_SelectHuo" +
            "danhaoResponse")]
        System.Data.DataSet frmPeiZaiFaHuoPeiZai_Insert_SelectHuodanhao();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PeiZaiFaHuoPeiZai_Insert/frmPeiZaiFaHuo_Insert_SelectcboWiangD" +
            "ian", ReplyAction="http://tempuri.org/PeiZaiFaHuoPeiZai_Insert/frmPeiZaiFaHuo_Insert_SelectcboWiangD" +
            "ianResponse")]
        System.Data.DataSet frmPeiZaiFaHuo_Insert_SelectcboWiangDian();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PeiZaiFaHuoPeiZai_Insert/frmPeiZaiFaHuo_Insert_SelectcboXianLu" +
            "", ReplyAction="http://tempuri.org/PeiZaiFaHuoPeiZai_Insert/frmPeiZaiFaHuo_Insert_SelectcboXianLu" +
            "Response")]
        System.Data.DataSet frmPeiZaiFaHuo_Insert_SelectcboXianLu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PeiZaiFaHuoPeiZai_Insert/frmPeiZaiFaHuo_Insert_SelectcboCheLia" +
            "ng", ReplyAction="http://tempuri.org/PeiZaiFaHuoPeiZai_Insert/frmPeiZaiFaHuo_Insert_SelectcboCheLia" +
            "ngResponse")]
        System.Data.DataSet frmPeiZaiFaHuo_Insert_SelectcboCheLiang();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PeiZaiFaHuoPeiZai_Insert/frmPeiZaiFaHuo_Insert_SelectSiJi", ReplyAction="http://tempuri.org/PeiZaiFaHuoPeiZai_Insert/frmPeiZaiFaHuo_Insert_SelectSiJiRespo" +
            "nse")]
        System.Data.DataSet frmPeiZaiFaHuo_Insert_SelectSiJi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PeiZaiFaHuoPeiZai_Insert/frmPeiZaiFaHuo_Insert_ConcelFenBaoSuo" +
            "Ding", ReplyAction="http://tempuri.org/PeiZaiFaHuoPeiZai_Insert/frmPeiZaiFaHuo_Insert_ConcelFenBaoSuo" +
            "DingResponse")]
        int frmPeiZaiFaHuo_Insert_ConcelFenBaoSuoDing(int 分包ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PeiZaiFaHuoPeiZai_Insert/cboFaHuoWangDian_SelectedIndexChanged" +
            "_ChaXunLuXianLinJu", ReplyAction="http://tempuri.org/PeiZaiFaHuoPeiZai_Insert/cboFaHuoWangDian_SelectedIndexChanged" +
            "_ChaXunLuXianLinJuResponse")]
        System.Data.DataSet cboFaHuoWangDian_SelectedIndexChanged_ChaXunLuXianLinJu(int 开始网点ID, int 结束网点ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PeiZaiFaHuoPeiZai_Insert/frmPeiZaiFaHuo_Insert_LockFenBaoSuoDi" +
            "ng", ReplyAction="http://tempuri.org/PeiZaiFaHuoPeiZai_Insert/frmPeiZaiFaHuo_Insert_LockFenBaoSuoDi" +
            "ngResponse")]
        int frmPeiZaiFaHuo_Insert_LockFenBaoSuoDing(int 分包ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PeiZaiFaHuoPeiZai_Insert/frmPeiZaiFaHuo_Insert_InsertPeiZaiFaC" +
            "he", ReplyAction="http://tempuri.org/PeiZaiFaHuoPeiZai_Insert/frmPeiZaiFaHuo_Insert_InsertPeiZaiFaC" +
            "heResponse")]
        int frmPeiZaiFaHuo_Insert_InsertPeiZaiFaChe(string 配载发车单号, int 车辆ID, int 司机ID, int 发车网点ID, int 线路ID, int 目的网点ID, System.DateTime 接单时间);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PeiZaiFaHuoPeiZai_Insert/frmPeiZaiFaHuo_Insert_InsertPeiZaiFaC" +
            "heMingXi", ReplyAction="http://tempuri.org/PeiZaiFaHuoPeiZai_Insert/frmPeiZaiFaHuo_Insert_InsertPeiZaiFaC" +
            "heMingXiResponse")]
        int frmPeiZaiFaHuo_Insert_InsertPeiZaiFaCheMingXi(int 配载发车单ID, int 分包ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PeiZaiFaHuoPeiZai_Insert/frmPeiZaiFaHuo_Insert_UpdateCheLiangZ" +
            "huangTai", ReplyAction="http://tempuri.org/PeiZaiFaHuoPeiZai_Insert/frmPeiZaiFaHuo_Insert_UpdateCheLiangZ" +
            "huangTaiResponse")]
        int frmPeiZaiFaHuo_Insert_UpdateCheLiangZhuangTai(int 车辆ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PeiZaiFaHuoPeiZai_Insert/frmPeiZaiFaHuo_Insert_UpdateSiJiZhuan" +
            "gTai", ReplyAction="http://tempuri.org/PeiZaiFaHuoPeiZai_Insert/frmPeiZaiFaHuo_Insert_UpdateSiJiZhuan" +
            "gTaiResponse")]
        int frmPeiZaiFaHuo_Insert_UpdateSiJiZhuangTai(int 司机ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PeiZaiFaHuoPeiZai_InsertChannel : WCF物流管理系统_Client.BLL物流管理系统.配载发货.PeiZaiFaHuoPeiZai_Insert.PeiZaiFaHuoPeiZai_Insert, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PeiZaiFaHuoPeiZai_InsertClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.配载发货.PeiZaiFaHuoPeiZai_Insert.PeiZaiFaHuoPeiZai_Insert>, WCF物流管理系统_Client.BLL物流管理系统.配载发货.PeiZaiFaHuoPeiZai_Insert.PeiZaiFaHuoPeiZai_Insert {
        
        public PeiZaiFaHuoPeiZai_InsertClient() {
        }
        
        public PeiZaiFaHuoPeiZai_InsertClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PeiZaiFaHuoPeiZai_InsertClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeiZaiFaHuoPeiZai_InsertClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeiZaiFaHuoPeiZai_InsertClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet frmPeiZaiFaHuoPeiZai_Insert_SelectHuodanhao() {
            return base.Channel.frmPeiZaiFaHuoPeiZai_Insert_SelectHuodanhao();
        }
        
        public System.Data.DataSet frmPeiZaiFaHuo_Insert_SelectcboWiangDian() {
            return base.Channel.frmPeiZaiFaHuo_Insert_SelectcboWiangDian();
        }
        
        public System.Data.DataSet frmPeiZaiFaHuo_Insert_SelectcboXianLu() {
            return base.Channel.frmPeiZaiFaHuo_Insert_SelectcboXianLu();
        }
        
        public System.Data.DataSet frmPeiZaiFaHuo_Insert_SelectcboCheLiang() {
            return base.Channel.frmPeiZaiFaHuo_Insert_SelectcboCheLiang();
        }
        
        public System.Data.DataSet frmPeiZaiFaHuo_Insert_SelectSiJi() {
            return base.Channel.frmPeiZaiFaHuo_Insert_SelectSiJi();
        }
        
        public int frmPeiZaiFaHuo_Insert_ConcelFenBaoSuoDing(int 分包ID) {
            return base.Channel.frmPeiZaiFaHuo_Insert_ConcelFenBaoSuoDing(分包ID);
        }
        
        public System.Data.DataSet cboFaHuoWangDian_SelectedIndexChanged_ChaXunLuXianLinJu(int 开始网点ID, int 结束网点ID) {
            return base.Channel.cboFaHuoWangDian_SelectedIndexChanged_ChaXunLuXianLinJu(开始网点ID, 结束网点ID);
        }
        
        public int frmPeiZaiFaHuo_Insert_LockFenBaoSuoDing(int 分包ID) {
            return base.Channel.frmPeiZaiFaHuo_Insert_LockFenBaoSuoDing(分包ID);
        }
        
        public int frmPeiZaiFaHuo_Insert_InsertPeiZaiFaChe(string 配载发车单号, int 车辆ID, int 司机ID, int 发车网点ID, int 线路ID, int 目的网点ID, System.DateTime 接单时间) {
            return base.Channel.frmPeiZaiFaHuo_Insert_InsertPeiZaiFaChe(配载发车单号, 车辆ID, 司机ID, 发车网点ID, 线路ID, 目的网点ID, 接单时间);
        }
        
        public int frmPeiZaiFaHuo_Insert_InsertPeiZaiFaCheMingXi(int 配载发车单ID, int 分包ID) {
            return base.Channel.frmPeiZaiFaHuo_Insert_InsertPeiZaiFaCheMingXi(配载发车单ID, 分包ID);
        }
        
        public int frmPeiZaiFaHuo_Insert_UpdateCheLiangZhuangTai(int 车辆ID) {
            return base.Channel.frmPeiZaiFaHuo_Insert_UpdateCheLiangZhuangTai(车辆ID);
        }
        
        public int frmPeiZaiFaHuo_Insert_UpdateSiJiZhuangTai(int 司机ID) {
            return base.Channel.frmPeiZaiFaHuo_Insert_UpdateSiJiZhuangTai(司机ID);
        }
    }
}
