//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34003
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.车辆状态.FRM_CheLiangZhuangTai_Insert {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.车辆状态.FRM_CheLiangZhuangTai_Insert.FRM_CheLiangZhuangTai_Insert")]
    public interface FRM_CheLiangZhuangTai_Insert {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangZhuangTai_Insert/FRM_CheLiangZhuangTai_Insert_Load" +
            "_ChaXunCheDui", ReplyAction="http://tempuri.org/FRM_CheLiangZhuangTai_Insert/FRM_CheLiangZhuangTai_Insert_Load" +
            "_ChaXunCheDuiResponse")]
        System.Data.DataSet FRM_CheLiangZhuangTai_Insert_Load_ChaXunCheDui();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangZhuangTai_Insert/FRM_CheLiangZhuangTai_Insert_Load" +
            "_ChaXunSiJi", ReplyAction="http://tempuri.org/FRM_CheLiangZhuangTai_Insert/FRM_CheLiangZhuangTai_Insert_Load" +
            "_ChaXunSiJiResponse")]
        System.Data.DataSet FRM_CheLiangZhuangTai_Insert_Load_ChaXunSiJi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangZhuangTai_Insert/btnBaoCun_Insert_Click_ChaRuCheLi" +
            "ang", ReplyAction="http://tempuri.org/FRM_CheLiangZhuangTai_Insert/btnBaoCun_Insert_Click_ChaRuCheLi" +
            "angResponse")]
        int btnBaoCun_Insert_Click_ChaRuCheLiang(string 车队ID, string 车牌号, string 行驶证号, string 保险证号, string 状态ID, string 发动机号, string 车架号, string 负责人_司机ID, string 紧急联系人_司机ID, byte[][] byteTuPian);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_CheLiangZhuangTai_InsertChannel : WCF物流管理系统_Client.BLL物流管理系统.车辆状态.FRM_CheLiangZhuangTai_Insert.FRM_CheLiangZhuangTai_Insert, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_CheLiangZhuangTai_InsertClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.车辆状态.FRM_CheLiangZhuangTai_Insert.FRM_CheLiangZhuangTai_Insert>, WCF物流管理系统_Client.BLL物流管理系统.车辆状态.FRM_CheLiangZhuangTai_Insert.FRM_CheLiangZhuangTai_Insert {
        
        public FRM_CheLiangZhuangTai_InsertClient() {
        }
        
        public FRM_CheLiangZhuangTai_InsertClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_CheLiangZhuangTai_InsertClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_CheLiangZhuangTai_InsertClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_CheLiangZhuangTai_InsertClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_CheLiangZhuangTai_Insert_Load_ChaXunCheDui() {
            return base.Channel.FRM_CheLiangZhuangTai_Insert_Load_ChaXunCheDui();
        }
        
        public System.Data.DataSet FRM_CheLiangZhuangTai_Insert_Load_ChaXunSiJi() {
            return base.Channel.FRM_CheLiangZhuangTai_Insert_Load_ChaXunSiJi();
        }
        
        public int btnBaoCun_Insert_Click_ChaRuCheLiang(string 车队ID, string 车牌号, string 行驶证号, string 保险证号, string 状态ID, string 发动机号, string 车架号, string 负责人_司机ID, string 紧急联系人_司机ID, byte[][] byteTuPian) {
            return base.Channel.btnBaoCun_Insert_Click_ChaRuCheLiang(车队ID, 车牌号, 行驶证号, 保险证号, 状态ID, 发动机号, 车架号, 负责人_司机ID, 紧急联系人_司机ID, byteTuPian);
        }
    }
}
