//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF物流管理系统_Client.BLL物流管理系统.线路管理.FRM_XianLuGuanLi_WangDianGuanLi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL物流管理系统.线路管理.FRM_XianLuGuanLi_WangDianGuanLi.FRM_XianLuGuanLi_WangDianGuanLi")]
    public interface FRM_XianLuGuanLi_WangDianGuanLi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_XianLuGuanLi_WangDianGuanLi/btnChaXunWangDianXinXi_Click_C" +
            "haXunWangDianXinXiONZhuangTai", ReplyAction="http://tempuri.org/FRM_XianLuGuanLi_WangDianGuanLi/btnChaXunWangDianXinXi_Click_C" +
            "haXunWangDianXinXiONZhuangTaiResponse")]
        System.Data.DataSet btnChaXunWangDianXinXi_Click_ChaXunWangDianXinXiONZhuangTai(string 停用否);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_XianLuGuanLi_WangDianGuanLi/btnChaXunWangDianXinXi_Click_C" +
            "haXunWangDianXinXi", ReplyAction="http://tempuri.org/FRM_XianLuGuanLi_WangDianGuanLi/btnChaXunWangDianXinXi_Click_C" +
            "haXunWangDianXinXiResponse")]
        System.Data.DataSet btnChaXunWangDianXinXi_Click_ChaXunWangDianXinXi(string 网点名称);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_XianLuGuanLi_WangDianGuanLi/dgvWangDianXinXi_CellClick_Cha" +
            "XunXiangLinWangDianXinXi", ReplyAction="http://tempuri.org/FRM_XianLuGuanLi_WangDianGuanLi/dgvWangDianXinXi_CellClick_Cha" +
            "XunXiangLinWangDianXinXiResponse")]
        System.Data.DataSet dgvWangDianXinXi_CellClick_ChaXunXiangLinWangDianXinXi(string 网点ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_XianLuGuanLi_WangDianGuanLi/tsbShanChu_Delete_Click_ShanCh" +
            "uWangDian", ReplyAction="http://tempuri.org/FRM_XianLuGuanLi_WangDianGuanLi/tsbShanChu_Delete_Click_ShanCh" +
            "uWangDianResponse")]
        int tsbShanChu_Delete_Click_ShanChuWangDian(string 网点ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_XianLuGuanLi_WangDianGuanLiChannel : WCF物流管理系统_Client.BLL物流管理系统.线路管理.FRM_XianLuGuanLi_WangDianGuanLi.FRM_XianLuGuanLi_WangDianGuanLi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_XianLuGuanLi_WangDianGuanLiClient : System.ServiceModel.ClientBase<WCF物流管理系统_Client.BLL物流管理系统.线路管理.FRM_XianLuGuanLi_WangDianGuanLi.FRM_XianLuGuanLi_WangDianGuanLi>, WCF物流管理系统_Client.BLL物流管理系统.线路管理.FRM_XianLuGuanLi_WangDianGuanLi.FRM_XianLuGuanLi_WangDianGuanLi {
        
        public FRM_XianLuGuanLi_WangDianGuanLiClient() {
        }
        
        public FRM_XianLuGuanLi_WangDianGuanLiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_XianLuGuanLi_WangDianGuanLiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_XianLuGuanLi_WangDianGuanLiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_XianLuGuanLi_WangDianGuanLiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet btnChaXunWangDianXinXi_Click_ChaXunWangDianXinXiONZhuangTai(string 停用否) {
            return base.Channel.btnChaXunWangDianXinXi_Click_ChaXunWangDianXinXiONZhuangTai(停用否);
        }
        
        public System.Data.DataSet btnChaXunWangDianXinXi_Click_ChaXunWangDianXinXi(string 网点名称) {
            return base.Channel.btnChaXunWangDianXinXi_Click_ChaXunWangDianXinXi(网点名称);
        }
        
        public System.Data.DataSet dgvWangDianXinXi_CellClick_ChaXunXiangLinWangDianXinXi(string 网点ID) {
            return base.Channel.dgvWangDianXinXi_CellClick_ChaXunXiangLinWangDianXinXi(网点ID);
        }
        
        public int tsbShanChu_Delete_Click_ShanChuWangDian(string 网点ID) {
            return base.Channel.tsbShanChu_Delete_Click_ShanChuWangDian(网点ID);
        }
    }
}
